"""Simple Markdown report helpers."""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import pandas as pd


def header(title: str, level: int = 1) -> str:
    return f"{'#' * level} {title}\n"


def bullet(text: str) -> str:
    return f"- {text}\n"


def code_block(text: str, language: str = "text") -> str:
    return f"```{language}\n{text}\n```\n"


def table_from_records(records: list[dict[str, Any]]) -> str:
    if not records:
        return "_No data._\n"
    df = pd.DataFrame(records)
    return str(df.to_markdown(index=False)) + "\n"


def write_report(path: Path, body: str, title: str | None = None) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    parts = [
        f"<!-- Generated by CrossPiezo Phase 0-4 pipeline at {datetime.now(tz=UTC).isoformat()} -->\n",
    ]
    if title:
        parts.append(f"# {title}\n")
    parts.append(body)
    path.write_text("\n".join(parts), encoding="utf-8")
