#!/usr/bin/env python
"""CrossPiezo Phase 7B: Screening Resolution v2 Methodological Upgrade.

This script computes Work Packages A-F and H from the Phase 7B taskbook and
writes only CSV/JSON results under ``artifacts/phase7b/`` and
``results/phase7b/``.  Report prose is generated by a separate renderer.

The script is read-only with respect to the frozen Phase 6A panel and source
parquets; it does not introduce new DFT, PULSE, PMR, componentwise/O(3), or
soft-mode causal claims.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import sys
import warnings
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import yaml
from pymatgen.core.structure import Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from scipy import stats

warnings.filterwarnings("ignore", category=UserWarning)

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SRC_ROOT = PROJECT_ROOT / "src"
CONFIG_ROOT = PROJECT_ROOT / "configs"
ARTIFACT_ROOT = PROJECT_ROOT / "artifacts" / "phase7b"
RESULT_ROOT = PROJECT_ROOT / "results" / "phase7b"
REPORT_ROOT = PROJECT_ROOT / "reports" / "phase7b"

sys.path.insert(0, str(SRC_ROOT))
sys.path.insert(0, str(PROJECT_ROOT))

from crosspiezo.analysis.phase7b_stats import (  # noqa: E402
    anion_group,
    benjamini_hochberg,
    grouped_paired_bootstrap_naucc,
    grouped_paired_bootstrap_tau,
    naucc,
    permutation_test_delta_tau,
    persistent_onset,
    portfolio_bootstrap_ci,
    portfolio_metrics,
    portfolio_select,
    q_consensus_pointwise,
    reduced_formula,
    screening_resolution_curve,
    tune_disagreement_abstention,
)
from crosspiezo.analysis.ranking import (  # noqa: E402
    chance_adjusted_jaccard,
    cohen_kappa,
    expected_jaccard_hypergeometric,
    frobenius_norm_score,
)
from crosspiezo.conventions.voigt import (  # noqa: E402
    trusted_piezo_stress_voigt_to_cartesian,
)

# -----------------------------------------------------------------------------
# Utilities
# -----------------------------------------------------------------------------


def _git_commit() -> str | None:
    try:
        return (
            __import__("subprocess")
            .check_output(["git", "rev-parse", "HEAD"], cwd=PROJECT_ROOT, text=True)
            .strip()
        )
    except Exception:  # noqa: BLE001
        return None


def _now() -> str:
    return datetime.now(tz=UTC).isoformat()


def _load_config() -> dict[str, Any]:
    with open(CONFIG_ROOT / "phase7b.yaml") as f:
        return yaml.safe_load(f)


def _resolve_data_root() -> Path:
    local = Path("E:/DATA")
    if local.exists():
        return local
    remote = Path.home() / "DATA"
    if remote.exists():
        return remote
    raise FileNotFoundError("Cannot locate data root (E:/DATA or ~/DATA)")


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def _write_csv_with_hash(df: pd.DataFrame, path: Path) -> dict[str, Any]:
    path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(path, index=False)
    return {"path": str(path.relative_to(PROJECT_ROOT)), "sha256": _sha256_file(path), "n_rows": len(df)}


def _to_array(value: Any) -> np.ndarray | None:
    if isinstance(value, np.ndarray):
        return np.asarray(value, dtype=np.float64)
    if isinstance(value, str):
        import ast

        parsed = ast.literal_eval(value)
        if isinstance(parsed, dict):
            for v in parsed.values():
                arr = _to_array(v)
                if arr is not None:
                    return arr
            return None
        return np.asarray(parsed, dtype=np.float64)
    if isinstance(value, (list, tuple)):
        return np.asarray(value, dtype=np.float64)
    return None


def _structure_volume(cif: str | None) -> float | None:
    if not cif:
        return None
    try:
        struct = Structure.from_str(cif, fmt="cif")
        return float(struct.volume / struct.composition.reduced_composition.num_atoms)
    except Exception:  # noqa: BLE001
        return None


def _dielectric_trace(tensor: Any) -> float | None:
    arr = _to_array(tensor)
    if arr is None:
        return None
    if arr.shape == (3, 3):
        return float(np.trace(arr))
    if arr.shape == (6,):
        return float(arr[0] + arr[1] + arr[2])
    return None


def _elastic_bulk_modulus_vrh(tensor: Any) -> float | None:
    """Voigt-Reuss-Hill bulk modulus from a 6x6 elastic tensor in GPa."""
    arr = _to_array(tensor)
    if arr is None or arr.shape != (6, 6):
        return None
    c = arr
    kv = (c[0, 0] + c[1, 1] + c[2, 2] + 2 * (c[0, 1] + c[1, 2] + c[0, 2])) / 9.0
    try:
        s = np.linalg.inv(c)
        kr = 1.0 / (s[0, 0] + s[1, 1] + s[2, 2] + 2 * (s[0, 1] + s[1, 2] + s[0, 2]))
    except Exception:  # noqa: BLE001
        return None
    if not np.isfinite(kr):
        return None
    return float(0.5 * (kv + kr))


def _crystal_system(cif: str | None) -> str:
    if not cif:
        return "unknown"
    try:
        struct = Structure.from_str(cif, fmt="cif")
        return SpacegroupAnalyzer(struct).get_crystal_system()
    except Exception:  # noqa: BLE001
        return "unknown"


def _heavy_atom_fraction(formula: str) -> float | None:
    if not formula:
        return None
    try:
        from pymatgen.core.composition import Composition

        comp = Composition(formula)
        total = sum(comp.values())
        heavy = sum(count for el, count in comp.items() if el.Z > 20)
        return float(heavy / total) if total else None
    except Exception:  # noqa: BLE001
        return None


def _hash_mod(value: str, n_splits: int) -> int:
    """Deterministic integer hash of a string modulo n_splits."""
    digest = hashlib.md5(str(value).encode("utf-8")).hexdigest()
    return int(digest, 16) % n_splits


# -----------------------------------------------------------------------------
# Data loading and enrichment
# -----------------------------------------------------------------------------


def load_panel() -> pd.DataFrame:
    cfg = _load_config()
    path = PROJECT_ROOT / cfg["panels"]["membership_path"]
    return pd.read_parquet(path)


def load_source_data(data_root: Path) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    root = data_root / "T2C-Flow"
    jarvis = pd.read_parquet(root / "processed" / "jarvis_piezo.parquet")
    mp = pd.read_parquet(root / "processed" / "materials_project_piezo.parquet")
    overlap = pd.read_parquet(root / "processed" / "jarvis_mp_piezo_overlap.parquet")
    return jarvis, mp, overlap


def build_enriched_panel(
    panel_df: pd.DataFrame,
    jarvis: pd.DataFrame,
    mp: pd.DataFrame,
) -> pd.DataFrame:
    """Merge panel with source-level property columns needed for controls."""
    jarvis = jarvis.copy()
    mp = mp.copy()
    jarvis["material_id"] = jarvis["material_id"].astype(str)
    mp["material_id"] = mp["material_id"].astype(str)

    jarvis_by_id = {str(row["material_id"]): row for _, row in jarvis.iterrows()}
    mp_by_id = {str(row["material_id"]): row for _, row in mp.iterrows()}

    rows: list[dict[str, Any]] = []
    for _, row in panel_df.iterrows():
        jid = str(row["jarvis_id"])
        mid = str(row["mp_id"])
        j = jarvis_by_id.get(jid, {})
        m = mp_by_id.get(mid, {})

        j_cif = j.get("cif")
        m_cif = m.get("cif")
        formula = row.get("formula")

        rec = {
            **row.to_dict(),
            "jarvis_band_gap": j.get("band_gap"),
            "mp_band_gap": m.get("band_gap"),
            "jarvis_energy_above_hull": j.get("energy_above_hull"),
            "mp_energy_above_hull": m.get("energy_above_hull"),
            "jarvis_volume_per_fu": _structure_volume(j_cif),
            "mp_volume_per_fu": _structure_volume(m_cif),
            "jarvis_dielectric_trace": _dielectric_trace(j.get("dielectric_total")),
            "mp_dielectric_trace": _dielectric_trace(m.get("dielectric_total")),
            "jarvis_bulk_modulus_vrh": _elastic_bulk_modulus_vrh(j.get("elastic_tensor")),
            "mp_bulk_modulus_vrh": _elastic_bulk_modulus_vrh(m.get("elastic_tensor")),
            "jarvis_crystal_system": _crystal_system(j_cif),
            "mp_crystal_system": _crystal_system(m_cif),
            "jarvis_space_group": j.get("space_group"),
            "mp_space_group": m.get("space_group"),
            "jarvis_cif": j_cif,
            "mp_cif": m_cif,
            "anion_group": anion_group(formula),
            "reduced_formula": reduced_formula(formula),
            "heavy_atom_fraction": _heavy_atom_fraction(formula),
        }
        rows.append(rec)
    return pd.DataFrame(rows)


# -----------------------------------------------------------------------------
# Work Package A: Screening-resolution curves
# -----------------------------------------------------------------------------


def _q_percentiles(cfg: dict[str, Any]) -> np.ndarray:
    sr = cfg["screening_resolution"]
    return np.arange(sr["q_percentiles"]["start"], sr["q_percentiles"]["stop"] + 1, sr["q_percentiles"]["step"])


def _panel_masks(enriched: pd.DataFrame, cfg: dict[str, Any]) -> dict[str, pd.Series]:
    masks: dict[str, pd.Series] = {}
    primary = cfg["panels"]["primary"]
    sensitivity = cfg["panels"]["sensitivity"]
    for base in (primary, sensitivity):
        masks[base] = enriched[base].astype(bool).copy()
        # High-response subset defined by pooled F1 response (reference metric).
        ref = cfg["property_controls"]["reference_piezo_metric"]
        metric = next(m for m in cfg["metrics"]["primary"] if m["name"] == ref)
        pooled = (enriched[metric["jarvis_col"]] + enriched[metric["mp_col"]]) / 2.0
        threshold = pooled.quantile(1.0 - cfg["panels"]["high_response_fraction"])
        masks[f"{base}{cfg['panels']['high_response_suffix']}"] = masks[base] & (pooled >= threshold)
    return masks


def run_wp_a(enriched: pd.DataFrame, cfg: dict[str, Any]) -> dict[str, Any]:
    print("[Phase 7B] Work Package A: screening-resolution curves...")
    q = _q_percentiles(cfg)
    sr = cfg["screening_resolution"]
    seed = sr["random_seed"]
    n_boot = sr["bootstrap_replicates"]
    alpha = 1.0 - sr["confidence_level"]
    delta_thresholds = sr["delta_thresholds"]
    metrics = cfg["metrics"]["primary"]
    panel_masks = _panel_masks(enriched, cfg)

    curve_rows: list[pd.DataFrame] = []
    summary_rows: list[dict[str, Any]] = []

    for panel_name, mask in panel_masks.items():
        sub = enriched[mask]
        for metric in metrics:
            left = sub[metric["jarvis_col"]].to_numpy()
            right = sub[metric["mp_col"]].to_numpy()
            curve = screening_resolution_curve(left, right, q, n_boot=n_boot, seed=seed, alpha=alpha)
            curve["panel"] = panel_name
            curve["metric"] = metric["name"]
            curve_rows.append(curve)

            summary: dict[str, Any] = {
                "panel": panel_name,
                "metric": metric["name"],
                "n_pairs": len(sub),
                "nAUCC": naucc(curve),
            }
            for delta in delta_thresholds:
                summary[f"q_consensus_delta{delta:.2f}"] = q_consensus_pointwise(curve, delta=delta)
                summary[f"persistent_onset_delta{delta:.2f}"] = persistent_onset(
                    curve, delta=delta, min_consecutive=sr["persistent_onset_min_consecutive"]
                )
            summary_rows.append(summary)

    curve_df = pd.concat(curve_rows, ignore_index=True)
    summary_df = pd.DataFrame(summary_rows)

    info = {
        "concordance_curve": _write_csv_with_hash(curve_df, RESULT_ROOT / "concordance_curve.csv"),
        "concordance_summary": _write_csv_with_hash(summary_df, RESULT_ROOT / "concordance_summary.csv"),
    }
    return info


# -----------------------------------------------------------------------------
# Work Package B: Scale / order / tail decomposition
# -----------------------------------------------------------------------------


def run_wp_b(enriched: pd.DataFrame, cfg: dict[str, Any]) -> dict[str, Any]:
    print("[Phase 7B] Work Package B: scale/order/tail decomposition...")
    metrics = cfg["metrics"]["primary"]
    panel_masks = _panel_masks(enriched, cfg)
    tail_frac = cfg["scale_order_tail"]["tail_fraction"]
    grid = np.arange(
        cfg["scale_order_tail"]["quantile_mapping_grid"]["start"],
        cfg["scale_order_tail"]["quantile_mapping_grid"]["stop"]
        + cfg["scale_order_tail"]["quantile_mapping_grid"]["step"],
        cfg["scale_order_tail"]["quantile_mapping_grid"]["step"],
    )
    records: list[dict[str, Any]] = []

    for panel_name, mask in panel_masks.items():
        sub = enriched[mask]
        for metric in metrics:
            left = sub[metric["jarvis_col"]].to_numpy()
            right = sub[metric["mp_col"]].to_numpy()
            valid = np.isfinite(left) & np.isfinite(right) & (left > 0) & (right > 0)
            l_arr, r_arr = left[valid], right[valid]
            n = len(l_arr)
            if n < 10:
                continue

            ratio = r_arr / l_arr
            log_diff = np.log(r_arr) - np.log(l_arr)
            tau_raw, _ = stats.kendalltau(l_arr, r_arr)
            rho_raw, _ = stats.spearmanr(l_arr, r_arr)
            pl = stats.rankdata(l_arr, method="average") / n
            pr = stats.rankdata(r_arr, method="average") / n
            tau_q, _ = stats.kendalltau(pl, pr)
            rho_q, _ = stats.spearmanr(pl, pr)

            k_tail = max(1, int(tail_frac * n))
            top_l = set(np.argsort(-l_arr, kind="stable")[:k_tail].tolist())
            top_r = set(np.argsort(-r_arr, kind="stable")[:k_tail].tolist())
            crossings = len(top_l.symmetric_difference(top_r))

            ranks_l = stats.rankdata(-l_arr, method="average")
            ranks_r = stats.rankdata(-r_arr, method="average")
            abs_shift = np.abs(ranks_l - ranks_r)

            # ECDF comparison.
            ks_stat, ks_p = stats.ks_2samp(l_arr, r_arr)

            # Quantile mapping value error (residual after monotonic calibration).
            q_l = np.quantile(l_arr, grid)
            q_r = np.quantile(r_arr, grid)
            qm_mae = float(np.mean(np.abs(q_r - q_l)))

            # Threshold agreement at the tail fraction.
            in_l = np.zeros(n, dtype=bool)
            in_r = np.zeros(n, dtype=bool)
            in_l[list(top_l)] = True
            in_r[list(top_r)] = True
            kappa = cohen_kappa(in_l, in_r)

            records.append(
                {
                    "panel": panel_name,
                    "metric": metric["name"],
                    "n_pairs": n,
                    "jarvis_median": float(np.median(l_arr)),
                    "mp_median": float(np.median(r_arr)),
                    "median_ratio_mp_over_jarvis": float(np.median(ratio)),
                    "mean_log_ratio": float(np.mean(log_diff)),
                    "median_log_ratio": float(np.median(log_diff)),
                    "kendall_tau_raw": float(tau_raw) if tau_raw is not None else float("nan"),
                    "spearman_rho_raw": float(rho_raw) if rho_raw is not None else float("nan"),
                    "kendall_tau_quantile_normalized": float(tau_q) if tau_q is not None else float("nan"),
                    "spearman_rho_quantile_normalized": float(rho_q) if rho_q is not None else float("nan"),
                    "top_10pct_threshold_crossings": crossings,
                    "top_10pct_k": k_tail,
                    "ecdf_ks_stat": float(ks_stat),
                    "ecdf_ks_pvalue": float(ks_p),
                    "quantile_mapping_value_error_mae": qm_mae,
                    "threshold_agreement_kappa_at_top10": float(kappa),
                    "mean_rank_displacement": float(np.mean(abs_shift)),
                    "median_rank_displacement": float(np.median(abs_shift)),
                }
            )

    df = pd.DataFrame(records)
    info = {"scale_order_tail": _write_csv_with_hash(df, RESULT_ROOT / "scale_order_tail.csv")}
    return info


# -----------------------------------------------------------------------------
# Work Package C: Property controls
# -----------------------------------------------------------------------------


def _control_source_fields(attr: dict[str, Any]) -> tuple[str, str]:
    """Return human-readable source field names for an attribute."""
    if attr["name"] == "volume":
        return "computed_from_cif", "computed_from_cif"
    return str(attr.get("jarvis_col") or "computed"), str(attr.get("mp_col") or "computed")


def _control_arrays(sub: pd.DataFrame, attr: dict[str, Any]) -> tuple[np.ndarray, np.ndarray]:
    name = attr["name"]
    if name == "volume":
        left = sub["jarvis_volume_per_fu"].to_numpy(dtype=float)
        right = sub["mp_volume_per_fu"].to_numpy(dtype=float)
    elif name == "band_gap":
        left = sub["jarvis_band_gap"].to_numpy(dtype=float)
        right = sub["mp_band_gap"].to_numpy(dtype=float)
    elif name == "energy_above_hull":
        left = sub["jarvis_energy_above_hull"].to_numpy(dtype=float)
        right = sub["mp_energy_above_hull"].to_numpy(dtype=float)
    elif name == "dielectric_total_trace":
        left = sub["jarvis_dielectric_trace"].to_numpy(dtype=float)
        right = sub["mp_dielectric_trace"].to_numpy(dtype=float)
    elif name == "elastic_bulk_modulus_vrh":
        left = sub["jarvis_bulk_modulus_vrh"].to_numpy(dtype=float)
        right = sub["mp_bulk_modulus_vrh"].to_numpy(dtype=float)
    else:
        left = np.full(len(sub), np.nan)
        right = np.full(len(sub), np.nan)
    return left, right


def _grouped_bootstrap_delta_tau(
    left_a: np.ndarray,
    right_a: np.ndarray,
    left_b: np.ndarray,
    right_b: np.ndarray,
    groups: np.ndarray,
    n_boot: int,
    seed: int,
) -> tuple[float, float, float]:
    """Bootstrap CI for tau_a - tau_b using group resampling."""
    groups = np.asarray(groups)
    unique_groups = np.unique(groups)
    if len(unique_groups) < 2:
        return float("nan"), float("nan"), float("nan")
    idx_by_group = {g: np.where(groups == g)[0] for g in unique_groups}
    rng = np.random.default_rng(seed)
    reps: list[float] = []
    for _ in range(n_boot):
        sampled = rng.choice(unique_groups, size=len(unique_groups), replace=True)
        idx = np.concatenate([idx_by_group[g] for g in sampled])
        if len(idx) < 5:
            continue
        # For each metric use rows where both sides are finite in the bootstrap sample.
        mask_a = np.isfinite(left_a[idx]) & np.isfinite(right_a[idx])
        mask_b = np.isfinite(left_b[idx]) & np.isfinite(right_b[idx])
        if mask_a.sum() < 5 or mask_b.sum() < 5:
            continue
        tau_a, _ = stats.kendalltau(left_a[idx][mask_a], right_a[idx][mask_a])
        tau_b, _ = stats.kendalltau(left_b[idx][mask_b], right_b[idx][mask_b])
        if tau_a is None or tau_b is None:
            continue
        reps.append(float(tau_a) - float(tau_b))
    if not reps:
        return float("nan"), float("nan"), float("nan")
    reps_arr = np.asarray(reps)
    point = float(np.mean(reps_arr))
    return point, float(np.percentile(reps_arr, 2.5)), float(np.percentile(reps_arr, 97.5))


def run_wp_c(enriched: pd.DataFrame, cfg: dict[str, Any]) -> dict[str, Any]:
    print("[Phase 7B] Work Package C: property controls...")
    q = _q_percentiles(cfg)
    pc = cfg["property_controls"]
    attrs = pc["attributes"]
    ref_name = pc["reference_piezo_metric"]
    ref_metric = next(m for m in cfg["metrics"]["primary"] if m["name"] == ref_name)
    seed = pc["grouped_bootstrap_seed"]
    n_boot = pc["grouped_bootstrap_replicates"]
    panel_masks = _panel_masks(enriched, cfg)

    curve_rows: list[pd.DataFrame] = []
    summary_rows: list[dict[str, Any]] = []
    comparison_rows: list[dict[str, Any]] = []

    for panel_name, mask in panel_masks.items():
        sub = enriched[mask].copy()
        groups = sub["reduced_formula"].to_numpy()

        # Reference piezo metric (F1).
        ref_left = sub[ref_metric["jarvis_col"]].to_numpy(dtype=float)
        ref_right = sub[ref_metric["mp_col"]].to_numpy(dtype=float)
        ref_tau, ref_tau_lo, ref_tau_hi = grouped_paired_bootstrap_tau(
            ref_left, ref_right, groups, n_boot=n_boot, seed=seed
        )
        ref_naucc, ref_naucc_lo, ref_naucc_hi = grouped_paired_bootstrap_naucc(
            ref_left, ref_right, q, groups, n_boot=n_boot, seed=seed
        )
        summary_rows.append(
            {
                "panel": panel_name,
                "attribute": ref_name,
                "required": True,
                "jarvis_source_field": ref_metric["jarvis_col"],
                "mp_source_field": ref_metric["mp_col"],
                "unit": "C/m^2",
                "common_n": int(np.isfinite(ref_left).sum()),
                "available_n": int(np.isfinite(ref_left).sum()),
                "status": "ok",
                "kendall_tau": ref_tau,
                "kendall_tau_ci95_low": ref_tau_lo,
                "kendall_tau_ci95_high": ref_tau_hi,
                "nAUCC": ref_naucc,
                "nAUCC_ci95_low": ref_naucc_lo,
                "nAUCC_ci95_high": ref_naucc_hi,
            }
        )

        panel_pvals: list[tuple[str, float]] = []
        for attr in attrs:
            name = attr["name"]
            left, right = _control_arrays(sub, attr)
            valid = np.isfinite(left) & np.isfinite(right)
            common_n = int(valid.sum())
            available_n = int(np.isfinite(left).sum() | np.isfinite(right).sum())
            jfield, mfield = _control_source_fields(attr)

            if common_n < 30:
                summary_rows.append(
                    {
                        "panel": panel_name,
                        "attribute": name,
                        "required": attr.get("required", False),
                        "jarvis_source_field": jfield,
                        "mp_source_field": mfield,
                        "unit": attr.get("unit", ""),
                        "common_n": common_n,
                        "available_n": available_n,
                        "status": "insufficient_N",
                        "kendall_tau": float("nan"),
                        "kendall_tau_ci95_low": float("nan"),
                        "kendall_tau_ci95_high": float("nan"),
                        "nAUCC": float("nan"),
                        "nAUCC_ci95_low": float("nan"),
                        "nAUCC_ci95_high": float("nan"),
                    }
                )
                continue

            tau, tau_lo, tau_hi = grouped_paired_bootstrap_tau(
                left, right, groups, n_boot=n_boot, seed=seed
            )
            naucc_val, naucc_lo, naucc_hi = grouped_paired_bootstrap_naucc(
                left, right, q, groups, n_boot=n_boot, seed=seed
            )
            curve = screening_resolution_curve(left, right, q, n_boot=0, seed=seed)
            curve["panel"] = panel_name
            curve["attribute"] = name
            curve_rows.append(curve)

            delta_tau = tau - ref_tau
            delta_naucc = naucc_val - ref_naucc
            pval = permutation_test_delta_tau(
                left, right, ref_left, ref_right, groups, n_perm=pc["permutation_replicates"], seed=pc["permutation_seed"]
            )
            panel_pvals.append((name, pval))
            delta_tau_point, delta_tau_lo, delta_tau_hi = _grouped_bootstrap_delta_tau(
                left, right, ref_left, ref_right, groups, n_boot=n_boot, seed=seed
            )

            summary_rows.append(
                {
                    "panel": panel_name,
                    "attribute": name,
                    "required": attr.get("required", False),
                    "jarvis_source_field": jfield,
                    "mp_source_field": mfield,
                    "unit": attr.get("unit", ""),
                    "common_n": common_n,
                    "available_n": available_n,
                    "status": "ok",
                    "kendall_tau": tau,
                    "kendall_tau_ci95_low": tau_lo,
                    "kendall_tau_ci95_high": tau_hi,
                    "nAUCC": naucc_val,
                    "nAUCC_ci95_low": naucc_lo,
                    "nAUCC_ci95_high": naucc_hi,
                    "Delta_tau": delta_tau,
                    "Delta_tau_ci95_low": delta_tau_lo,
                    "Delta_tau_ci95_high": delta_tau_hi,
                    "Delta_nAUCC": delta_naucc,
                    "permutation_pvalue": pval,
                }
            )

        # FDR across controls (exclude reference metric).
        names, pvals = zip(*panel_pvals, strict=False) if panel_pvals else ([], [])
        if pvals:
            qvals = benjamini_hochberg(list(pvals))
            for name, qval in zip(names, qvals, strict=True):
                comparison_rows.append(
                    {
                        "panel": panel_name,
                        "attribute": name,
                        "reference_metric": ref_name,
                        "fdr_qvalue": qval,
                    }
                )

    summary_df = pd.DataFrame(summary_rows)
    curve_df = pd.concat(curve_rows, ignore_index=True) if curve_rows else pd.DataFrame()
    comp_df = pd.DataFrame(comparison_rows)

    info = {"property_controls": _write_csv_with_hash(summary_df, RESULT_ROOT / "property_controls.csv")}
    if not curve_df.empty:
        info["property_control_curves"] = _write_csv_with_hash(curve_df, RESULT_ROOT / "property_control_curves.csv")
    if not comp_df.empty:
        info["property_control_comparison"] = _write_csv_with_hash(comp_df, RESULT_ROOT / "property_control_comparison.csv")
    return info


# -----------------------------------------------------------------------------
# Work Package D: Electronic / ionic decomposition
# -----------------------------------------------------------------------------


def _tensor_from_source(
    row: pd.Series,
    source_by_id: dict[str, pd.Series],
    side: str,
    contrib: str,
) -> np.ndarray | None:
    rec = source_by_id.get(str(row[f"{side}_id"]))
    if rec is None:
        return None
    voigt = _to_array(rec.get(f"piezo_voigt_{contrib}"))
    if voigt is None or voigt.shape != (3, 6):
        return None
    try:
        return trusted_piezo_stress_voigt_to_cartesian(voigt)
    except Exception:  # noqa: BLE001
        return None


def run_wp_d(enriched: pd.DataFrame, cfg: dict[str, Any]) -> dict[str, Any]:
    print("[Phase 7B] Work Package D: electronic/ionic decomposition...")
    data_root = _resolve_data_root()
    jarvis, mp, _ = load_source_data(data_root)
    jarvis_by_id = {str(r["material_id"]): r for _, r in jarvis.iterrows()}
    mp_by_id = {str(r["material_id"]): r for _, r in mp.iterrows()}

    min_n = cfg["electronic_ionic"]["min_effective_n"]
    contributions = cfg["electronic_ionic"]["contributions"]
    panel_masks = {
        cfg["panels"]["primary"]: enriched[cfg["panels"]["primary"]],
        cfg["panels"]["sensitivity"]: enriched[cfg["panels"]["sensitivity"]],
    }

    rows: list[dict[str, Any]] = []
    for panel_name, mask in panel_masks.items():
        sub = enriched[mask]
        for contrib in contributions:
            left: list[np.ndarray] = []
            right: list[np.ndarray] = []
            for _, row in sub.iterrows():
                lt = _tensor_from_source(row, jarvis_by_id, "jarvis", contrib)
                rt = _tensor_from_source(row, mp_by_id, "mp", contrib)
                if lt is None or rt is None:
                    continue
                left.append(lt)
                right.append(rt)
            n = len(left)
            if n < min_n:
                rows.append(
                    {
                        "panel": panel_name,
                        "contribution": contrib,
                        "effective_n": n,
                        "status": "insufficient_N",
                        "kendall_tau": float("nan"),
                        "top_10pct_adjusted_jaccard": float("nan"),
                    }
                )
                continue
            l_f1 = np.array([frobenius_norm_score(t) for t in left])
            r_f1 = np.array([frobenius_norm_score(t) for t in right])
            tau, _ = stats.kendalltau(l_f1, r_f1)
            k10 = max(1, int(0.10 * n))
            tl = set(np.argsort(-l_f1, kind="stable")[:k10].tolist())
            tr = set(np.argsort(-r_f1, kind="stable")[:k10].tolist())
            inter = len(tl & tr)
            oj = inter / len(tl | tr)
            ej = expected_jaccard_hypergeometric(n, k10)
            aj = chance_adjusted_jaccard(oj, ej)
            rows.append(
                {
                    "panel": panel_name,
                    "contribution": contrib,
                    "effective_n": n,
                    "status": "ok",
                    "kendall_tau": float(tau) if tau is not None else float("nan"),
                    "top_10pct_adjusted_jaccard": aj,
                }
            )

    df = pd.DataFrame(rows)
    info = {"electronic_ionic_decomposition": _write_csv_with_hash(df, RESULT_ROOT / "electronic_ionic_decomposition.csv")}
    return info


# -----------------------------------------------------------------------------
# Work Package E: Heterogeneity and match sensitivity
# -----------------------------------------------------------------------------


def _subgroup_permutation_p(
    left: np.ndarray,
    right: np.ndarray,
    mask: np.ndarray,
    n_perm: int,
    seed: int,
) -> float:
    """Pair-level permutation p-value for tau_subgroup == tau_complement."""
    left = np.asarray(left, dtype=np.float64)
    right = np.asarray(right, dtype=np.float64)
    mask = np.asarray(mask, dtype=bool)
    n = len(left)
    tau_sub, _ = stats.kendalltau(left[mask], right[mask])
    tau_comp, _ = stats.kendalltau(left[~mask], right[~mask])
    if tau_sub is None or tau_comp is None:
        return float("nan")
    observed = float(tau_sub) - float(tau_comp)
    rng = np.random.default_rng(seed)
    b = 0
    for _ in range(n_perm):
        perm = rng.permutation(n)
        perm_mask = np.zeros(n, dtype=bool)
        perm_mask[perm[:mask.sum()]] = True
        t_sub, _ = stats.kendalltau(left[perm_mask], right[perm_mask])
        t_comp, _ = stats.kendalltau(left[~perm_mask], right[~perm_mask])
        if t_sub is None or t_comp is None:
            continue
        if abs(float(t_sub) - float(t_comp)) >= abs(observed):
            b += 1
    return (b + 1) / (n_perm + 1)


def run_wp_e(enriched: pd.DataFrame, cfg: dict[str, Any]) -> dict[str, Any]:
    print("[Phase 7B] Work Package E: heterogeneity and match sensitivity...")
    metrics = cfg["metrics"]["primary"]
    panel_masks = {
        cfg["panels"]["primary"]: enriched[cfg["panels"]["primary"]],
        cfg["panels"]["sensitivity"]: enriched[cfg["panels"]["sensitivity"]],
    }
    min_n = cfg["heterogeneity"]["subgroup_min_n"]
    n_boot = cfg["heterogeneity"]["grouped_bootstrap_replicates"]
    seed = cfg["heterogeneity"]["grouped_bootstrap_seed"]
    n_perm = cfg["heterogeneity"]["permutation_replicates"]
    perm_seed = cfg["heterogeneity"]["permutation_seed"]

    records: list[dict[str, Any]] = []
    continuous_records: list[dict[str, Any]] = []

    for panel_name, mask in panel_masks.items():
        sub = enriched[mask].copy()
        for metric in metrics:
            left = sub[metric["jarvis_col"]].to_numpy(dtype=float)
            right = sub[metric["mp_col"]].to_numpy(dtype=float)
            valid = np.isfinite(left) & np.isfinite(right)
            subv = sub[valid].copy()
            left, right = left[valid], right[valid]
            if len(left) < min_n:
                continue
            groups = subv["reduced_formula"].to_numpy()
            tau_full, tau_full_lo, tau_full_hi = grouped_paired_bootstrap_tau(
                left, right, groups, n_boot=n_boot, seed=seed
            )

            # Crystal system (prefer JARVIS, fall back to MP).
            subv["crystal_system_use"] = subv["jarvis_crystal_system"].fillna(subv["mp_crystal_system"])
            for crystal_sys in subv["crystal_system_use"].dropna().unique():
                smask = (subv["crystal_system_use"] == crystal_sys).to_numpy()
                if smask.sum() < min_n:
                    continue
                tau, lo, hi = grouped_paired_bootstrap_tau(
                    left[smask], right[smask], groups[smask], n_boot=n_boot, seed=seed
                )
                records.append(
                    _heterogeneity_record(
                        panel_name, metric["name"], "crystal_system", crystal_sys, smask.sum(),
                        tau, lo, hi, tau_full, left, right, smask, n_perm, perm_seed
                    )
                )

            # Anion group.
            for ag in subv["anion_group"].dropna().unique():
                smask = (subv["anion_group"] == ag).to_numpy()
                if smask.sum() < min_n:
                    continue
                tau, lo, hi = grouped_paired_bootstrap_tau(
                    left[smask], right[smask], groups[smask], n_boot=n_boot, seed=seed
                )
                records.append(
                    _heterogeneity_record(
                        panel_name, metric["name"], "anion_group", ag, smask.sum(),
                        tau, lo, hi, tau_full, left, right, smask, n_perm, perm_seed
                    )
                )

            # Response magnitude quartile (pooled across sources).
            pooled = (left + right) / 2.0
            q25, q50, q75 = np.quantile(pooled, [0.25, 0.5, 0.75])
            bins = [
                ("Q1_low", left <= q25),
                ("Q2", (left > q25) & (left <= q50)),
                ("Q3", (left > q50) & (left <= q75)),
                ("Q4_high", left > q75),
            ]
            for label, bmask in bins:
                if bmask.sum() < min_n:
                    continue
                tau, lo, hi = grouped_paired_bootstrap_tau(
                    left[bmask], right[bmask], groups[bmask], n_boot=n_boot, seed=seed
                )
                records.append(
                    _heterogeneity_record(
                        panel_name, metric["name"], "response_magnitude_quartile", label, bmask.sum(),
                        tau, lo, hi, tau_full, left, right, bmask, n_perm, perm_seed
                    )
                )

            # Match quality terciles.
            for cov, prefix in [("rms_distance", "rms_match_quality"), ("lattice_distance", "lattice_match_quality")]:
                vals = subv[cov].to_numpy(dtype=float)
                finite_vals = vals[np.isfinite(vals)]
                if len(finite_vals) < min_n:
                    continue
                t1, t2 = np.quantile(finite_vals, [1 / 3, 2 / 3])
                mq_bins = [
                    ("best_match", vals <= t1),
                    ("mid_match", (vals > t1) & (vals <= t2)),
                    ("loose_match", vals > t2),
                ]
                for label, mmask in mq_bins:
                    if mmask.sum() < min_n:
                        continue
                    tau, lo, hi = grouped_paired_bootstrap_tau(
                        left[mmask], right[mmask], groups[mmask], n_boot=n_boot, seed=seed
                    )
                    records.append(
                        _heterogeneity_record(
                            panel_name, metric["name"], prefix, label, mmask.sum(),
                            tau, lo, hi, tau_full, left, right, mmask, n_perm, perm_seed
                        )
                    )

            # Heavy-atom fraction terciles.
            haf = subv["heavy_atom_fraction"].to_numpy(dtype=float)
            finite_haf = haf[np.isfinite(haf)]
            if len(finite_haf) >= min_n:
                t1, t2 = np.quantile(finite_haf, [1 / 3, 2 / 3])
                h_bins = [
                    ("low_heavy", haf <= t1),
                    ("mid_heavy", (haf > t1) & (haf <= t2)),
                    ("high_heavy", haf > t2),
                ]
                for label, hmask in h_bins:
                    if hmask.sum() < min_n:
                        continue
                    tau, lo, hi = grouped_paired_bootstrap_tau(
                        left[hmask], right[hmask], groups[hmask], n_boot=n_boot, seed=seed
                    )
                    records.append(
                        _heterogeneity_record(
                            panel_name, metric["name"], "heavy_atom_fraction", label, hmask.sum(),
                            tau, lo, hi, tau_full, left, right, hmask, n_perm, perm_seed
                        )
                    )

            # Continuous mismatch analysis.
            ranks_l = stats.rankdata(-left, method="average")
            ranks_r = stats.rankdata(-right, method="average")
            abs_shift = np.abs(ranks_l - ranks_r)
            for cov in cfg["heterogeneity"]["continuous_covariates"]:
                vals = subv[cov].to_numpy(dtype=float)
                cmask = np.isfinite(vals) & np.isfinite(abs_shift)
                if cmask.sum() < min_n:
                    continue
                tau_c, _ = stats.kendalltau(vals[cmask], abs_shift[cmask])
                rho_c, _ = stats.spearmanr(vals[cmask], abs_shift[cmask])
                continuous_records.append(
                    {
                        "panel": panel_name,
                        "metric": metric["name"],
                        "continuous_covariate": cov,
                        "n": int(cmask.sum()),
                        "kendall_tau_vs_rank_shift": float(tau_c) if tau_c is not None else float("nan"),
                        "spearman_rho_vs_rank_shift": float(rho_c) if rho_c is not None else float("nan"),
                    }
                )

    df = pd.DataFrame(records)
    if not df.empty:
        # FDR correction within each panel/metric/covariate grouping.
        for (_panel, _metric, _cov), g in df.groupby(["panel", "metric", "covariate"]):
            pvals = g["permutation_pvalue"].tolist()
            df.loc[g.index, "fdr_qvalue"] = benjamini_hochberg(pvals)

    cont_df = pd.DataFrame(continuous_records)
    info = {"heterogeneity": _write_csv_with_hash(df, RESULT_ROOT / "heterogeneity.csv")}
    if not cont_df.empty:
        info["heterogeneity_continuous"] = _write_csv_with_hash(cont_df, RESULT_ROOT / "heterogeneity_continuous.csv")
    return info


def _heterogeneity_record(
    panel: str,
    metric: str,
    covariate: str,
    group: str,
    n: int,
    tau: float,
    tau_lo: float,
    tau_hi: float,
    tau_full: float,
    left: np.ndarray,
    right: np.ndarray,
    mask: np.ndarray,
    n_perm: int,
    perm_seed: int,
) -> dict[str, Any]:
    pval = _subgroup_permutation_p(left, right, mask, n_perm, perm_seed)
    return {
        "panel": panel,
        "metric": metric,
        "covariate": covariate,
        "group": group,
        "n": n,
        "kendall_tau": tau,
        "kendall_tau_ci95_low": tau_lo,
        "kendall_tau_ci95_high": tau_hi,
        "delta_tau_vs_full": float(tau - tau_full) if np.isfinite(tau) and np.isfinite(tau_full) else float("nan"),
        "permutation_pvalue": pval,
        "fdr_qvalue": float("nan"),
    }


# -----------------------------------------------------------------------------
# Work Package F: Robust portfolio strategies
# -----------------------------------------------------------------------------


def _portfolio_split(sub: pd.DataFrame, n_splits: int, holdout_fold: int) -> tuple[pd.DataFrame, pd.DataFrame]:
    folds = sub["pair_id"].apply(lambda x: _hash_mod(x, n_splits))
    dev = sub[folds != holdout_fold].copy()
    hold = sub[folds == holdout_fold].copy()
    return dev, hold


def _pareto_frontier(df: pd.DataFrame, recall_col: str, coverage_col: str) -> pd.DataFrame:
    """Flag non-dominated points (higher recall and higher coverage is better)."""
    df = df.copy()
    df["pareto_efficient"] = False
    points = df[[recall_col, coverage_col]].to_numpy(dtype=float)
    for i, (r, c) in enumerate(points):
        dominated = False
        for j, (rj, cj) in enumerate(points):
            if i == j:
                continue
            if rj >= r and cj >= c and (rj > r or cj > c):
                dominated = True
                break
        df.loc[df.index[i], "pareto_efficient"] = not dominated
    return df


def run_wp_f(enriched: pd.DataFrame, cfg: dict[str, Any]) -> dict[str, Any]:
    print("[Phase 7B] Work Package F: robust portfolio strategies...")
    rp = cfg["robust_portfolio"]
    q_star = rp["q_star"]
    budgets = rp["budgets"]
    strategies = rp["strategies"]
    metrics = cfg["metrics"]["primary"]
    n_splits = rp["n_splits"]
    holdout_fold = rp["holdout_fold"]
    n_boot = rp["grouped_bootstrap_replicates"]
    seed = rp["grouped_bootstrap_seed"]
    lambda_grid = rp["disagreement_abstention"]["lambda_grid"]
    tune_n_boot = 200

    panel_masks = {
        cfg["panels"]["primary"]: enriched[cfg["panels"]["primary"]],
        cfg["panels"]["sensitivity"]: enriched[cfg["panels"]["sensitivity"]],
    }

    records: list[dict[str, Any]] = []
    for panel_name, mask in panel_masks.items():
        for metric in metrics:
            sub = enriched[mask].copy()
            left = sub[metric["jarvis_col"]].to_numpy(dtype=float)
            right = sub[metric["mp_col"]].to_numpy(dtype=float)
            valid = np.isfinite(left) & np.isfinite(right)
            sub = sub[valid].copy()
            left, right = left[valid], right[valid]
            if len(left) < 20:
                continue

            dev, hold = _portfolio_split(sub, n_splits, holdout_fold)
            if len(hold) < 10 or len(dev) < 10:
                continue
            dev_groups = dev["reduced_formula"].to_numpy()
            hold_groups = hold["reduced_formula"].to_numpy()

            for budget_factor in budgets:
                tuned_lambda: float | None = None
                for strategy in strategies:
                    lam = 0.0
                    if strategy == "disagreement_abstention":
                        lam = tune_disagreement_abstention(
                            dev[metric["jarvis_col"]].to_numpy(dtype=float),
                            dev[metric["mp_col"]].to_numpy(dtype=float),
                            q_star,
                            budget_factor,
                            lambda_grid,
                            dev_groups,
                            n_boot=tune_n_boot,
                            seed=seed,
                        )
                        tuned_lambda = lam

                    h_left = hold[metric["jarvis_col"]].to_numpy(dtype=float)
                    h_right = hold[metric["mp_col"]].to_numpy(dtype=float)
                    selected = portfolio_select(
                        strategy, h_left, h_right, q_star, budget_factor, lambda_param=lam
                    )
                    metrics_dict = portfolio_metrics(selected, h_left, h_right, q_star)
                    ci = portfolio_bootstrap_ci(
                        strategy,
                        h_left,
                        h_right,
                        q_star,
                        budget_factor,
                        hold_groups,
                        n_boot=n_boot,
                        seed=seed,
                        lambda_param=lam,
                    )

                    target_k = max(1, int(math.floor(q_star * len(h_left))))
                    budget = min(len(h_left), int(round(budget_factor * target_k)))
                    rec: dict[str, Any] = {
                        "panel": panel_name,
                        "metric": metric["name"],
                        "strategy": strategy,
                        "budget_factor": budget_factor,
                        "target_k": target_k,
                        "budget": budget,
                        "holdout_n": len(hold),
                        "disagreement_lambda": tuned_lambda if strategy == "disagreement_abstention" else float("nan"),
                    }
                    rec.update(metrics_dict)
                    for mkey in (
                        "worst_source_recall",
                        "worst_source_ndcg",
                        "worst_source_normalized_utility",
                        "minimax_recall_regret",
                        "minimax_ndcg_regret",
                        "portfolio_coverage",
                    ):
                        rec[f"{mkey}_ci95_low"] = ci.get(mkey, {}).get("ci95_low", float("nan"))
                        rec[f"{mkey}_ci95_high"] = ci.get(mkey, {}).get("ci95_high", float("nan"))
                    records.append(rec)

    df = pd.DataFrame(records)
    info = {"portfolio_benchmark": _write_csv_with_hash(df, RESULT_ROOT / "portfolio_benchmark.csv")}

    # Pareto frontier: coverage vs worst-source recall per (panel, metric, budget_factor).
    if not df.empty:
        frontier_rows: list[pd.DataFrame] = []
        for (_panel, _metric, _bf), g in df.groupby(["panel", "metric", "budget_factor"]):
            frontier_rows.append(_pareto_frontier(g, "worst_source_recall", "portfolio_coverage"))
        pareto_df = pd.concat(frontier_rows, ignore_index=True)
        info["portfolio_pareto"] = _write_csv_with_hash(pareto_df, RESULT_ROOT / "portfolio_pareto.csv")
    return info


# -----------------------------------------------------------------------------
# Work Package H: CCF-A method concept note
# -----------------------------------------------------------------------------


def run_wp_h(cfg: dict[str, Any]) -> dict[str, Any]:
    print("[Phase 7B] Work Package H: CCF-A method concept note...")
    md = """# CCF-A Method Paper Concept: Source-Robust Ranking under Conflicting Scientific Labels (v0.2)

## 1. General problem

Multiple independent computational protocols, database versions, or experimental assays can assign conflicting labels or scores to the same material.  Existing ranking methods optimise agreement with a single source and are not guaranteed to produce candidates that are robust across sources.  The generic task is:

> Given noisy, source-conditional score vectors for a shared set of items, learn a ranking or selection rule whose top-k performance is stable under the worst source.

This is a methodological, benchmark-driven problem: we do not assume access to a single physical ground truth.

## 2. Core research questions

1. When does cross-source disagreement reflect irreducible convention differences versus reducible noise?
2. Can a source-robust ranking objective guarantee a target worst-source recall without oracle labels?
3. Which protocols (abstention, distributionally robust optimisation, rank aggregation, held-out-source validation) yield measurable gains on real multi-source benchmarks?

## 3. Candidate methods

- **Distributionally robust optimisation (DRO) ranking**: minimise worst-source ranking loss over a source uncertainty set.
- **Set-valued labels**: treat each item's label as an interval or set across sources and define conservative dominance relations.
- **Abstention**: allow the model to decline ranking items with high cross-source disagreement.
- **Rank aggregation with source reliability**: learn source weights from held-out-source validation.
- **Deterministic robust portfolios**: explicit two-source selection rules (maximin, balanced union, disagreement abstention) with finite-sample regret bounds.

## 4. Theoretical propositions

1. **Rank-correlation upper bound**: for any deterministic ranking, worst-source NDCG@k is bounded above by a monotone function of source-source Kendall tau and the elite fraction q*.
2. **Abstention guarantee**: under a bounded-disagreement model, there exists an abstention rule that achieves a target worst-source recall at a quantifiable coverage cost.
3. **DRO generalisation**: DRO ranking generalises across sources if the source distribution shift is bounded in Wasserstein or Jensen-Shannon divergence.
4. **Portfolio minimax regret**: for two sources, the greedy maximin-oracle portfolio has minimax recall regret no larger than the single-source oracle that ignores the other source.

## 5. Multi-source benchmarks (at least three)

1. **CrossPiezo** (piezoelectric response, JARVIS vs Materials Project) — current project, frozen matched-pair panels P0/P2.
2. **MatBench-Dielectric / MP + AFLOW + OQMD elastic moduli** — scalar property, three independent high-throughput sources.
3. **Perovskite band gaps** from different DFT functionals and high-throughput experiments — mixed computational/experimental source labels.

## 6. Baselines

- Single-source ranker trained on pooled data.
- Borda / Copeland rank aggregation.
- Domain-adversarial or source-conditioned neural ranker.
- Conservative maximin selection.
- Oracle single-source upper bound (for regret calibration only).

## 7. Held-out-source protocol

- Train on a subset of sources; validate on a held-out source.
- Report worst-source and average-source Recall@k, NDCG@k, and minimax regret.
- Require that improvements are not due to test-set leakage from shared upstream data.
- CrossPiezo-specific: deterministic grouped split by hashed pair_id; disagreement-abstention lambda tuned on dev and evaluated on a frozen holdout.

## 8. Computational budget

- Data scale: 1k-10k matched items per benchmark.
- Model scale: light-weight neural ranker or gradient-boosted ranker; no large language models required.
- Compute: CPU/GPU training within a few GPU-days per benchmark.

## 9. Method Go / No-Go risks

**Go**: Theoretical bounds are non-vacuous, worst-source gains exceed 10% over single-source baselines on at least two benchmarks, and abstention meaningfully reduces regret while preserving coverage.

**No-Go**: Disagreement is dominated by irreducible convention errors, worst-source performance cannot be improved without oracle source labels, or benchmarks lack held-out-source independence.
"""
    out_path = PROJECT_ROOT / cfg["outputs"]["ccfa_concept"]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(md, encoding="utf-8")
    info = {"ccfa_concept": {"path": str(out_path.relative_to(PROJECT_ROOT))}}
    print(f"[Phase 7B] Wrote {info['ccfa_concept']['path']}")
    return info


# -----------------------------------------------------------------------------
# Manifest and main
# -----------------------------------------------------------------------------


def _result_hashes() -> list[dict[str, Any]]:
    hashes = []
    for path in sorted(RESULT_ROOT.glob("*.csv")):
        hashes.append({"path": str(path.relative_to(PROJECT_ROOT)), "sha256": _sha256_file(path)})
    for path in sorted(RESULT_ROOT.glob("*.json")):
        hashes.append({"path": str(path.relative_to(PROJECT_ROOT)), "sha256": _sha256_file(path)})
    return hashes


def _key_numbers(summaries: dict[str, pd.DataFrame]) -> dict[str, Any]:
    numbers: dict[str, Any] = {}
    conc = summaries.get("concordance_summary")
    if conc is not None and not conc.empty:
        row = conc[(conc["panel"] == "P0") & (conc["metric"] == "F1_Frobenius")]
        if not row.empty:
            numbers["P0_F1_nAUCC"] = float(row.iloc[0]["nAUCC"])
            numbers["P0_F1_persistent_onset_delta0.05"] = row.iloc[0].get("persistent_onset_delta0.05")
    port = summaries.get("portfolio_benchmark")
    if port is not None and not port.empty:
        best = port.loc[port["worst_source_recall"].idxmax()]
        numbers["best_holdout_worst_source_recall"] = float(best["worst_source_recall"])
        numbers["best_holdout_strategy"] = str(best["strategy"])
    return numbers


def write_manifest(summaries: dict[str, pd.DataFrame], cfg: dict[str, Any]) -> dict[str, Any]:
    manifest = {
        "timestamp": _now(),
        "commit": _git_commit(),
        "config_commit": cfg["metadata"]["baseline_commit"],
        "branch": cfg["metadata"]["branch"],
        "files": _result_hashes(),
        "key_numbers": _key_numbers(summaries),
    }
    path = RESULT_ROOT / "phase7b_manifest.json"
    path.write_text(json.dumps(manifest, indent=2, default=str), encoding="utf-8")
    return {"manifest": {"path": str(path.relative_to(PROJECT_ROOT))}}


def main() -> int:
    parser = argparse.ArgumentParser(description="Run CrossPiezo Phase 7B")
    parser.add_argument("--dry-run", action="store_true", help="Print plan without writing files")
    args = parser.parse_args()

    cfg = _load_config()
    if args.dry_run:
        print("[dry-run] Phase 7B would run A-F/H work packages and write outputs to:")
        print(f"  artifacts: {ARTIFACT_ROOT}")
        print(f"  results:   {RESULT_ROOT}")
        print(f"  reports:   {REPORT_ROOT}")
        return 0

    ARTIFACT_ROOT.mkdir(parents=True, exist_ok=True)
    RESULT_ROOT.mkdir(parents=True, exist_ok=True)
    REPORT_ROOT.mkdir(parents=True, exist_ok=True)
    (ARTIFACT_ROOT / "figures").mkdir(parents=True, exist_ok=True)

    commit = _git_commit()
    print(f"[Phase 7B] commit={commit}")

    panel_df = load_panel()
    data_root = _resolve_data_root()
    jarvis, mp, _ = load_source_data(data_root)
    enriched = build_enriched_panel(panel_df, jarvis, mp)

    summaries: dict[str, pd.DataFrame] = {}

    info_a = run_wp_a(enriched, cfg)
    summaries["concordance_curve"] = pd.read_csv(RESULT_ROOT / "concordance_curve.csv")
    summaries["concordance_summary"] = pd.read_csv(RESULT_ROOT / "concordance_summary.csv")

    info_b = run_wp_b(enriched, cfg)
    summaries["scale_order_tail"] = pd.read_csv(RESULT_ROOT / "scale_order_tail.csv")

    info_c = run_wp_c(enriched, cfg)
    summaries["property_controls"] = pd.read_csv(RESULT_ROOT / "property_controls.csv")

    info_d = run_wp_d(enriched, cfg)
    summaries["electronic_ionic"] = pd.read_csv(RESULT_ROOT / "electronic_ionic_decomposition.csv")

    info_e = run_wp_e(enriched, cfg)
    summaries["heterogeneity"] = pd.read_csv(RESULT_ROOT / "heterogeneity.csv")

    info_f = run_wp_f(enriched, cfg)
    summaries["portfolio_benchmark"] = pd.read_csv(RESULT_ROOT / "portfolio_benchmark.csv")

    info_h = run_wp_h(cfg)

    info_manifest = write_manifest(summaries, cfg)

    print("[Phase 7B] Completed.")
    print(
        json.dumps(
            {
                "commit": commit,
                "A": info_a,
                "B": info_b,
                "C": info_c,
                "D": info_d,
                "E": info_e,
                "F": info_f,
                "H": info_h,
                "manifest": info_manifest,
            },
            indent=2,
            default=str,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
