#!/usr/bin/env python
"""CrossPiezo Phase 7C: Reviewer-Proofing and Q1 Decision.

This script computes Work Packages A-F from the Phase 7C taskbook and writes
only CSV/JSON results under ``artifacts/phase7c/`` and ``results/phase7c/``.
Report prose is generated by a separate renderer.

The script is read-only with respect to the frozen Phase 6A panel and source
parquets; it does not introduce new DFT, PULSE, PMR, componentwise/O(3), or
soft-mode causal claims.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import sys
import warnings
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import yaml
from pymatgen.core.structure import Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from scipy import stats

warnings.filterwarnings("ignore", category=UserWarning)

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SRC_ROOT = PROJECT_ROOT / "src"
CONFIG_ROOT = PROJECT_ROOT / "configs"
ARTIFACT_ROOT = PROJECT_ROOT / "artifacts" / "phase7c"
RESULT_ROOT = PROJECT_ROOT / "results" / "phase7c"
REPORT_ROOT = PROJECT_ROOT / "reports" / "phase7c"

sys.path.insert(0, str(SRC_ROOT))
sys.path.insert(0, str(PROJECT_ROOT))

from crosspiezo.analysis.phase7b_stats import (  # noqa: E402
    anion_group,
    benjamini_hochberg,
    grouped_paired_bootstrap_naucc,
    grouped_paired_bootstrap_tau,
    naucc,
    persistent_onset,
    portfolio_metrics,
    portfolio_select,
    q_consensus_pointwise,
    screening_resolution_curve,
    tune_disagreement_abstention,
)
from crosspiezo.analysis.phase7c_stats import (  # noqa: E402
    anchor_high_response_mask,
    conditional_permutation_high_response,
    control_provenance_record,
    dual_high_response_mask,
    full_procedure_portfolio_bootstrap_ci,
    material_level_paired_diff_ci,
    paired_bootstrap_ci_difference,
    partial_naucc,
    portfolio_cross_evaluation,
)

# -----------------------------------------------------------------------------
# Utilities
# -----------------------------------------------------------------------------


def _git_commit() -> str | None:
    try:
        return (
            __import__("subprocess")
            .check_output(["git", "rev-parse", "HEAD"], cwd=PROJECT_ROOT, text=True)
            .strip()
        )
    except Exception:  # noqa: BLE001
        return None


def _now() -> str:
    return datetime.now(tz=UTC).isoformat()


def _load_config() -> dict[str, Any]:
    with open(CONFIG_ROOT / "phase7c.yaml") as f:
        return yaml.safe_load(f)


def _resolve_data_root() -> Path:
    local = Path("E:/DATA")
    if local.exists():
        return local
    remote = Path.home() / "DATA"
    if remote.exists():
        return remote
    raise FileNotFoundError("Cannot locate data root (E:/DATA or ~/DATA)")


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def _write_csv_with_hash(df: pd.DataFrame, path: Path) -> dict[str, Any]:
    path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(path, index=False)
    return {"path": str(path.relative_to(PROJECT_ROOT)), "sha256": _sha256_file(path), "n_rows": len(df)}


def _write_json_with_hash(data: dict[str, Any], path: Path) -> dict[str, Any]:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, default=str), encoding="utf-8")
    return {"path": str(path.relative_to(PROJECT_ROOT)), "sha256": _sha256_file(path)}


def _to_array(value: Any) -> np.ndarray | None:
    if isinstance(value, np.ndarray):
        return np.asarray(value, dtype=np.float64)
    if isinstance(value, str):
        import ast

        parsed = ast.literal_eval(value)
        if isinstance(parsed, dict):
            for v in parsed.values():
                arr = _to_array(v)
                if arr is not None:
                    return arr
            return None
        return np.asarray(parsed, dtype=np.float64)
    if isinstance(value, (list, tuple)):
        return np.asarray(value, dtype=np.float64)
    return None


def _structure_volume(cif: str | None) -> float | None:
    if not cif:
        return None
    try:
        struct = Structure.from_str(cif, fmt="cif")
        return float(struct.volume / struct.composition.reduced_composition.num_atoms)
    except Exception:  # noqa: BLE001
        return None


def _dielectric_trace(tensor: Any) -> float | None:
    arr = _to_array(tensor)
    if arr is None:
        return None
    if arr.shape == (3, 3):
        return float(np.trace(arr))
    if arr.shape == (6,):
        return float(arr[0] + arr[1] + arr[2])
    return None


def _elastic_bulk_modulus_vrh(tensor: Any) -> float | None:
    """Voigt-Reuss-Hill bulk modulus from a 6x6 elastic tensor in GPa."""
    arr = _to_array(tensor)
    if arr is None or arr.shape != (6, 6):
        return None
    c = arr
    kv = (c[0, 0] + c[1, 1] + c[2, 2] + 2 * (c[0, 1] + c[1, 2] + c[0, 2])) / 9.0
    try:
        s = np.linalg.inv(c)
        kr = 1.0 / (s[0, 0] + s[1, 1] + s[2, 2] + 2 * (s[0, 1] + s[1, 2] + s[0, 2]))
    except Exception:  # noqa: BLE001
        return None
    if not np.isfinite(kr):
        return None
    return float(0.5 * (kv + kr))


def _crystal_system(cif: str | None) -> str:
    if not cif:
        return "unknown"
    try:
        struct = Structure.from_str(cif, fmt="cif")
        return SpacegroupAnalyzer(struct).get_crystal_system()
    except Exception:  # noqa: BLE001
        return "unknown"


def _heavy_atom_fraction(formula: str) -> float | None:
    if not formula:
        return None
    try:
        from pymatgen.core.composition import Composition

        comp = Composition(formula)
        total = sum(comp.values())
        heavy = sum(count for el, count in comp.items() if el.Z > 20)
        return float(heavy / total) if total else None
    except Exception:  # noqa: BLE001
        return None


def _hash_mod(value: str, n_splits: int) -> int:
    """Deterministic integer hash of a string modulo n_splits."""
    digest = hashlib.md5(str(value).encode("utf-8")).hexdigest()
    return int(digest, 16) % n_splits


# -----------------------------------------------------------------------------
# Data loading and enrichment
# -----------------------------------------------------------------------------


def load_panel() -> pd.DataFrame:
    cfg = _load_config()
    path = PROJECT_ROOT / cfg["panels"]["membership_path"]
    return pd.read_parquet(path)


def load_source_data(data_root: Path) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    root = data_root / "T2C-Flow"
    jarvis = pd.read_parquet(root / "processed" / "jarvis_piezo.parquet")
    mp = pd.read_parquet(root / "processed" / "materials_project_piezo.parquet")
    overlap = pd.read_parquet(root / "processed" / "jarvis_mp_piezo_overlap.parquet")
    return jarvis, mp, overlap


def build_enriched_panel(
    panel_df: pd.DataFrame,
    jarvis: pd.DataFrame,
    mp: pd.DataFrame,
) -> pd.DataFrame:
    """Merge panel with source-level property columns needed for controls."""
    jarvis = jarvis.copy()
    mp = mp.copy()
    jarvis["material_id"] = jarvis["material_id"].astype(str)
    mp["material_id"] = mp["material_id"].astype(str)

    jarvis_by_id = {str(row["material_id"]): row for _, row in jarvis.iterrows()}
    mp_by_id = {str(row["material_id"]): row for _, row in mp.iterrows()}

    rows: list[dict[str, Any]] = []
    for _, row in panel_df.iterrows():
        jid = str(row["jarvis_id"])
        mid = str(row["mp_id"])
        j = jarvis_by_id.get(jid, {})
        m = mp_by_id.get(mid, {})

        j_cif = j.get("cif")
        m_cif = m.get("cif")
        formula = row.get("formula")

        rec = {
            **row.to_dict(),
            "jarvis_band_gap": j.get("band_gap"),
            "mp_band_gap": m.get("band_gap"),
            "jarvis_energy_above_hull": j.get("energy_above_hull"),
            "mp_energy_above_hull": m.get("energy_above_hull"),
            "jarvis_volume_per_fu": _structure_volume(j_cif),
            "mp_volume_per_fu": _structure_volume(m_cif),
            "jarvis_dielectric_trace": _dielectric_trace(j.get("dielectric_total")),
            "mp_dielectric_trace": _dielectric_trace(m.get("dielectric_total")),
            "jarvis_bulk_modulus_vrh": _elastic_bulk_modulus_vrh(j.get("elastic_tensor")),
            "mp_bulk_modulus_vrh": _elastic_bulk_modulus_vrh(m.get("elastic_tensor")),
            "jarvis_crystal_system": _crystal_system(j_cif),
            "mp_crystal_system": _crystal_system(m_cif),
            "jarvis_space_group": j.get("space_group"),
            "mp_space_group": m.get("space_group"),
            "jarvis_cif": j_cif,
            "mp_cif": m_cif,
            "anion_group": anion_group(formula),
            "reduced_formula": None,  # filled below
            "heavy_atom_fraction": _heavy_atom_fraction(formula),
        }
        rows.append(rec)
    df = pd.DataFrame(rows)
    df["reduced_formula"] = df["formula"].apply(lambda f: _reduced_formula(f))
    return df


def _reduced_formula(formula: str | None) -> str | None:
    if not formula:
        return None
    try:
        from pymatgen.core.composition import Composition

        return Composition(formula).reduced_formula
    except Exception:  # noqa: BLE001
        return None


# -----------------------------------------------------------------------------
# Common helpers
# -----------------------------------------------------------------------------


def _q_percentiles(cfg: dict[str, Any]) -> np.ndarray:
    sr = cfg["screening_resolution"]
    return np.arange(sr["q_percentiles"]["start"], sr["q_percentiles"]["stop"] + 1, sr["q_percentiles"]["step"])


def _panel_masks(enriched: pd.DataFrame, cfg: dict[str, Any]) -> dict[str, pd.Series]:
    masks: dict[str, pd.Series] = {}
    primary = cfg["panels"]["primary"]
    sensitivity = cfg["panels"]["sensitivity"]
    masks[primary] = enriched[primary].astype(bool).copy()
    masks[sensitivity] = enriched[sensitivity].astype(bool).copy()
    return masks


# -----------------------------------------------------------------------------
# Work Package A: Full screening-resolution curves with bands
# -----------------------------------------------------------------------------


def run_wp_a(enriched: pd.DataFrame, cfg: dict[str, Any]) -> dict[str, Any]:
    print("[Phase 7C] Work Package A: screening-resolution curves and bands...")
    q = _q_percentiles(cfg)
    sr = cfg["screening_resolution"]
    seed = sr["random_seed"]
    n_boot = sr["bootstrap_replicates"]
    alpha = 1.0 - sr["confidence_level"]
    delta_thresholds = sr["delta_thresholds"]
    min_consecutive = sr["persistent_onset_min_consecutive"]
    metrics = cfg["metrics"]["primary"]
    bands = sr["bands"]
    panel_masks = _panel_masks(enriched, cfg)

    curve_rows: list[pd.DataFrame] = []
    summary_rows: list[dict[str, Any]] = []
    band_rows: list[dict[str, Any]] = []

    for panel_name, mask in panel_masks.items():
        sub = enriched[mask]
        for metric in metrics:
            left = sub[metric["jarvis_col"]].to_numpy(dtype=float)
            right = sub[metric["mp_col"]].to_numpy(dtype=float)
            curve = screening_resolution_curve(left, right, q, n_boot=n_boot, seed=seed, alpha=alpha)
            curve["panel"] = panel_name
            curve["metric"] = metric["name"]
            curve_rows.append(curve)

            summary: dict[str, Any] = {
                "panel": panel_name,
                "metric": metric["name"],
                "n_pairs": len(sub),
                "nAUCC": naucc(curve),
            }
            for delta in delta_thresholds:
                summary[f"q_consensus_delta{delta:.2f}"] = q_consensus_pointwise(curve, delta=delta)
                summary[f"persistent_onset_delta{delta:.2f}"] = persistent_onset(
                    curve, delta=delta, min_consecutive=min_consecutive
                )
            summary_rows.append(summary)

            for band in bands:
                band_rows.append(
                    {
                        "panel": panel_name,
                        "metric": metric["name"],
                        "band": band["name"],
                        "q_min": band["q_min"],
                        "q_max": band["q_max"],
                        "partial_nAUCC": partial_naucc(curve, band["q_min"], band["q_max"]),
                    }
                )

    curve_df = pd.concat(curve_rows, ignore_index=True)
    summary_df = pd.DataFrame(summary_rows)
    band_df = pd.DataFrame(band_rows)

    info = {
        "concordance_curve": _write_csv_with_hash(curve_df, RESULT_ROOT / "concordance_curve.csv"),
        "concordance_summary": _write_csv_with_hash(summary_df, RESULT_ROOT / "concordance_summary.csv"),
        "concordance_bands": _write_csv_with_hash(band_df, RESULT_ROOT / "concordance_bands.csv"),
    }
    return info


# -----------------------------------------------------------------------------
# Work Package B: Corrected high-response sensitivity
# -----------------------------------------------------------------------------


def _high_response_subset_metrics(
    left: np.ndarray,
    right: np.ndarray,
    groups: np.ndarray,
    mask: np.ndarray,
    q: np.ndarray,
    n_boot: int,
    seed: int,
) -> dict[str, Any]:
    """Grouped bootstrap tau and nAUCC for a selected high-response subset."""
    if mask.sum() < 10:
        return {
            "n_selected": int(mask.sum()),
            "kendall_tau": float("nan"),
            "kendall_tau_ci95_low": float("nan"),
            "kendall_tau_ci95_high": float("nan"),
            "nAUCC": float("nan"),
            "nAUCC_ci95_low": float("nan"),
            "nAUCC_ci95_high": float("nan"),
        }
    tau, tau_lo, tau_hi = grouped_paired_bootstrap_tau(
        left[mask], right[mask], groups[mask], n_boot=n_boot, seed=seed
    )
    naucc_val, naucc_lo, naucc_hi = grouped_paired_bootstrap_naucc(
        left[mask], right[mask], q, groups[mask], n_boot=n_boot, seed=seed
    )
    return {
        "n_selected": int(mask.sum()),
        "kendall_tau": tau,
        "kendall_tau_ci95_low": tau_lo,
        "kendall_tau_ci95_high": tau_hi,
        "nAUCC": naucc_val,
        "nAUCC_ci95_low": naucc_lo,
        "nAUCC_ci95_high": naucc_hi,
    }


def run_wp_b(enriched: pd.DataFrame, cfg: dict[str, Any]) -> dict[str, Any]:
    print("[Phase 7C] Work Package B: corrected high-response sensitivity...")
    q = _q_percentiles(cfg)
    metrics = cfg["metrics"]["primary"]
    fractions = cfg["high_response"]["fractions"]
    hr_cfg = cfg["high_response"]
    n_perm = hr_cfg["conditional_permutation"]["n_perm"]
    perm_seed = hr_cfg["conditional_permutation"]["seed"]
    n_boot = cfg["statistics"]["bootstrap_replicates"]
    boot_seed = cfg["statistics"]["random_seed"]
    panel_masks = _panel_masks(enriched, cfg)

    records: list[dict[str, Any]] = []

    for panel_name, mask in panel_masks.items():
        sub = enriched[mask].copy()
        groups = sub["reduced_formula"].to_numpy()
        for metric in metrics:
            left = sub[metric["jarvis_col"]].to_numpy(dtype=float)
            right = sub[metric["mp_col"]].to_numpy(dtype=float)
            for fraction in fractions:
                # Dual-high subset.
                dual_mask = dual_high_response_mask(left, right, fraction)
                dual = _high_response_subset_metrics(
                    left, right, groups, dual_mask, q, n_boot, boot_seed
                )
                records.append(
                    {
                        "panel": panel_name,
                        "metric": metric["name"],
                        "fraction": fraction,
                        "method": "dual_high",
                        **dual,
                        "permuted_mean_naucc": float("nan"),
                        "permutation_pvalue": float("nan"),
                        "note": "both sources exceed min-quantile threshold",
                    }
                )

                # JARVIS anchor.
                jarvis_mask = anchor_high_response_mask(left, right, fraction)
                jarvis_anchor = _high_response_subset_metrics(
                    left, right, groups, jarvis_mask, q, n_boot, boot_seed
                )
                records.append(
                    {
                        "panel": panel_name,
                        "metric": metric["name"],
                        "fraction": fraction,
                        "method": "jarvis_anchor",
                        **jarvis_anchor,
                        "permuted_mean_naucc": float("nan"),
                        "permutation_pvalue": float("nan"),
                        "note": "top fraction by JARVIS, evaluated on MP",
                    }
                )

                # MP anchor.
                mp_mask = anchor_high_response_mask(right, left, fraction)
                mp_anchor = _high_response_subset_metrics(
                    left, right, groups, mp_mask, q, n_boot, boot_seed
                )
                records.append(
                    {
                        "panel": panel_name,
                        "metric": metric["name"],
                        "fraction": fraction,
                        "method": "mp_anchor",
                        **mp_anchor,
                        "permuted_mean_naucc": float("nan"),
                        "permutation_pvalue": float("nan"),
                        "note": "top fraction by MP, evaluated on JARVIS",
                    }
                )

                # Pooled exploratory with conditional permutation.
                perm = conditional_permutation_high_response(
                    left, right, fraction, q_percentiles=q, n_perm=n_perm, seed=perm_seed
                )
                records.append(
                    {
                        "panel": panel_name,
                        "metric": metric["name"],
                        "fraction": fraction,
                        "method": "pooled_exploratory",
                        "n_selected": perm["n_selected"],
                        "kendall_tau": float("nan"),
                        "kendall_tau_ci95_low": float("nan"),
                        "kendall_tau_ci95_high": float("nan"),
                        "nAUCC": perm["observed_naucc"],
                        "nAUCC_ci95_low": float("nan"),
                        "nAUCC_ci95_high": float("nan"),
                        "permuted_mean_naucc": perm["permuted_mean_naucc"],
                        "permutation_pvalue": perm["p_value"],
                        "note": "legacy pooled selection; exploratory only",
                    }
                )

    df = pd.DataFrame(records)
    info = {"high_response_sensitivity": _write_csv_with_hash(df, RESULT_ROOT / "high_response_sensitivity.csv")}
    return info


# -----------------------------------------------------------------------------
# Work Package C: Property controls with provenance audit
# -----------------------------------------------------------------------------


def _control_source_fields(attr: dict[str, Any]) -> tuple[str, str]:
    """Return human-readable source field names for an attribute."""
    if attr["name"] == "volume":
        return "computed_from_cif", "computed_from_cif"
    return str(attr.get("jarvis_col") or "computed"), str(attr.get("mp_col") or "computed")


def _control_calculation_type_version(attr: dict[str, Any]) -> str:
    """Human-readable calculation provenance string."""
    name = attr["name"]
    if name == "volume":
        return "computed_from_relaxed_cif"
    if name == "band_gap":
        return "DFT_PBE"
    if name == "energy_above_hull":
        return "DFT_phase_diagram"
    if name == "dielectric_total_trace":
        return "DFPT_dielectric_tensor_trace"
    if name == "elastic_bulk_modulus_vrh":
        return "DFPT_elastic_tensor_VRH_bulk"
    return "unknown"


def _control_arrays(sub: pd.DataFrame, attr: dict[str, Any]) -> tuple[np.ndarray, np.ndarray]:
    name = attr["name"]
    if name == "volume":
        left = sub["jarvis_volume_per_fu"].to_numpy(dtype=float)
        right = sub["mp_volume_per_fu"].to_numpy(dtype=float)
    elif name == "band_gap":
        left = sub["jarvis_band_gap"].to_numpy(dtype=float)
        right = sub["mp_band_gap"].to_numpy(dtype=float)
    elif name == "energy_above_hull":
        left = sub["jarvis_energy_above_hull"].to_numpy(dtype=float)
        right = sub["mp_energy_above_hull"].to_numpy(dtype=float)
    elif name == "dielectric_total_trace":
        left = sub["jarvis_dielectric_trace"].to_numpy(dtype=float)
        right = sub["mp_dielectric_trace"].to_numpy(dtype=float)
    elif name == "elastic_bulk_modulus_vrh":
        left = sub["jarvis_bulk_modulus_vrh"].to_numpy(dtype=float)
        right = sub["mp_bulk_modulus_vrh"].to_numpy(dtype=float)
    else:
        left = np.full(len(sub), np.nan)
        right = np.full(len(sub), np.nan)
    return left, right


def _grouped_bootstrap_delta_tau(
    left_a: np.ndarray,
    right_a: np.ndarray,
    left_b: np.ndarray,
    right_b: np.ndarray,
    groups: np.ndarray,
    n_boot: int,
    seed: int,
) -> tuple[float, float, float]:
    """Bootstrap CI for tau_a - tau_b using group resampling."""
    groups = np.asarray(groups)
    unique_groups = np.unique(groups)
    if len(unique_groups) < 2:
        return float("nan"), float("nan"), float("nan")
    idx_by_group = {g: np.where(groups == g)[0] for g in unique_groups}
    rng = np.random.default_rng(seed)
    reps: list[float] = []
    for _ in range(n_boot):
        sampled = rng.choice(unique_groups, size=len(unique_groups), replace=True)
        idx = np.concatenate([idx_by_group[g] for g in sampled])
        if len(idx) < 5:
            continue
        mask_a = np.isfinite(left_a[idx]) & np.isfinite(right_a[idx])
        mask_b = np.isfinite(left_b[idx]) & np.isfinite(right_b[idx])
        if mask_a.sum() < 5 or mask_b.sum() < 5:
            continue
        tau_a, _ = stats.kendalltau(left_a[idx][mask_a], right_a[idx][mask_a])
        tau_b, _ = stats.kendalltau(left_b[idx][mask_b], right_b[idx][mask_b])
        if tau_a is None or tau_b is None:
            continue
        reps.append(float(tau_a) - float(tau_b))
    if not reps:
        return float("nan"), float("nan"), float("nan")
    reps_arr = np.asarray(reps)
    point = float(np.mean(reps_arr))
    return point, float(np.percentile(reps_arr, 2.5)), float(np.percentile(reps_arr, 97.5))


def run_wp_c(enriched: pd.DataFrame, cfg: dict[str, Any]) -> dict[str, Any]:
    print("[Phase 7C] Work Package C: property controls with provenance audit...")
    q = _q_percentiles(cfg)
    pc = cfg["property_controls"]
    attrs = pc["attributes"]
    ref_name = pc["reference_piezo_metric"]
    ref_metric = next(m for m in cfg["metrics"]["primary"] if m["name"] == ref_name)
    seed = pc["grouped_bootstrap_seed"]
    n_boot = pc["grouped_bootstrap_replicates"]
    panel_masks = _panel_masks(enriched, cfg)

    curve_rows: list[pd.DataFrame] = []
    summary_rows: list[dict[str, Any]] = []
    comparison_rows: list[dict[str, Any]] = []
    provenance_rows: list[dict[str, Any]] = []

    for panel_name, mask in panel_masks.items():
        sub = enriched[mask].copy()
        groups = sub["reduced_formula"].to_numpy()

        # Reference piezo metric (F1).
        ref_left = sub[ref_metric["jarvis_col"]].to_numpy(dtype=float)
        ref_right = sub[ref_metric["mp_col"]].to_numpy(dtype=float)
        ref_tau, ref_tau_lo, ref_tau_hi = grouped_paired_bootstrap_tau(
            ref_left, ref_right, groups, n_boot=n_boot, seed=seed
        )
        ref_naucc, ref_naucc_lo, ref_naucc_hi = grouped_paired_bootstrap_naucc(
            ref_left, ref_right, q, groups, n_boot=n_boot, seed=seed
        )
        summary_rows.append(
            {
                "panel": panel_name,
                "attribute": ref_name,
                "required": True,
                "jarvis_source_field": ref_metric["jarvis_col"],
                "mp_source_field": ref_metric["mp_col"],
                "unit": "C/m^2",
                "common_n": int(np.isfinite(ref_left).sum()),
                "available_n": int(np.isfinite(ref_left).sum()),
                "status": "ok",
                "kendall_tau": ref_tau,
                "kendall_tau_ci95_low": ref_tau_lo,
                "kendall_tau_ci95_high": ref_tau_hi,
                "nAUCC": ref_naucc,
                "nAUCC_ci95_low": ref_naucc_lo,
                "nAUCC_ci95_high": ref_naucc_hi,
            }
        )

        panel_pvals: list[tuple[str, float]] = []
        for attr in attrs:
            name = attr["name"]
            left, right = _control_arrays(sub, attr)
            valid = np.isfinite(left) & np.isfinite(right)
            common_n = int(valid.sum())
            available_n = int(np.isfinite(left).sum() | np.isfinite(right).sum())
            jfield, mfield = _control_source_fields(attr)

            # Provenance audit record (always written).
            prov = control_provenance_record(
                attr_name=name,
                jarvis_col=jfield,
                mp_col=mfield,
                jarvis_source_db="JARVIS",
                mp_source_db="Materials_Project",
                unit=attr.get("unit", ""),
                calculation_type_version=_control_calculation_type_version(attr),
                jarvis_arr=left,
                mp_arr=right,
            )
            prov["panel"] = panel_name
            provenance_rows.append(prov)

            if common_n < 30:
                summary_rows.append(
                    {
                        "panel": panel_name,
                        "attribute": name,
                        "required": attr.get("required", False),
                        "jarvis_source_field": jfield,
                        "mp_source_field": mfield,
                        "unit": attr.get("unit", ""),
                        "common_n": common_n,
                        "available_n": available_n,
                        "status": "insufficient_N",
                        "kendall_tau": float("nan"),
                        "kendall_tau_ci95_low": float("nan"),
                        "kendall_tau_ci95_high": float("nan"),
                        "nAUCC": float("nan"),
                        "nAUCC_ci95_low": float("nan"),
                        "nAUCC_ci95_high": float("nan"),
                    }
                )
                continue

            tau, tau_lo, tau_hi = grouped_paired_bootstrap_tau(
                left, right, groups, n_boot=n_boot, seed=seed
            )
            naucc_val, naucc_lo, naucc_hi = grouped_paired_bootstrap_naucc(
                left, right, q, groups, n_boot=n_boot, seed=seed
            )
            curve = screening_resolution_curve(left, right, q, n_boot=0, seed=seed)
            curve["panel"] = panel_name
            curve["attribute"] = name
            curve_rows.append(curve)

            delta_tau = tau - ref_tau
            delta_naucc = naucc_val - ref_naucc
            pval = _permutation_test_delta_tau(
                left, right, ref_left, ref_right, groups, n_perm=pc["permutation_replicates"], seed=pc["permutation_seed"]
            )
            panel_pvals.append((name, pval))
            delta_tau_point, delta_tau_lo, delta_tau_hi = _grouped_bootstrap_delta_tau(
                left, right, ref_left, ref_right, groups, n_boot=n_boot, seed=seed
            )

            summary_rows.append(
                {
                    "panel": panel_name,
                    "attribute": name,
                    "required": attr.get("required", False),
                    "jarvis_source_field": jfield,
                    "mp_source_field": mfield,
                    "unit": attr.get("unit", ""),
                    "common_n": common_n,
                    "available_n": available_n,
                    "status": "ok",
                    "kendall_tau": tau,
                    "kendall_tau_ci95_low": tau_lo,
                    "kendall_tau_ci95_high": tau_hi,
                    "nAUCC": naucc_val,
                    "nAUCC_ci95_low": naucc_lo,
                    "nAUCC_ci95_high": naucc_hi,
                    "Delta_tau": delta_tau,
                    "Delta_tau_ci95_low": delta_tau_lo,
                    "Delta_tau_ci95_high": delta_tau_hi,
                    "Delta_nAUCC": delta_naucc,
                    "permutation_pvalue": pval,
                }
            )

        # FDR across controls (exclude reference metric).
        names, pvals = zip(*panel_pvals, strict=False) if panel_pvals else ([], [])
        if pvals:
            qvals = benjamini_hochberg(list(pvals))
            for name, qval in zip(names, qvals, strict=True):
                comparison_rows.append(
                    {
                        "panel": panel_name,
                        "attribute": name,
                        "reference_metric": ref_name,
                        "fdr_qvalue": qval,
                    }
                )

    summary_df = pd.DataFrame(summary_rows)
    curve_df = pd.concat(curve_rows, ignore_index=True) if curve_rows else pd.DataFrame()
    comp_df = pd.DataFrame(comparison_rows)
    prov_df = pd.DataFrame(provenance_rows)

    info = {
        "property_controls": _write_csv_with_hash(summary_df, RESULT_ROOT / "property_controls.csv"),
        "control_provenance": _write_csv_with_hash(prov_df, RESULT_ROOT / "control_provenance.csv"),
    }
    if not curve_df.empty:
        info["property_control_curves"] = _write_csv_with_hash(curve_df, RESULT_ROOT / "property_control_curves.csv")
    if not comp_df.empty:
        info["property_control_comparison"] = _write_csv_with_hash(comp_df, RESULT_ROOT / "property_control_comparison.csv")
    return info


def _permutation_test_delta_tau(
    left_ctrl: np.ndarray,
    right_ctrl: np.ndarray,
    left_piezo: np.ndarray,
    right_piezo: np.ndarray,
    groups: np.ndarray,
    n_perm: int = 4999,
    seed: int = 43,
) -> float:
    """Group-label permutation p-value for H0: tau_ctrl == tau_piezo."""
    left_ctrl = np.asarray(left_ctrl, dtype=np.float64)
    right_ctrl = np.asarray(right_ctrl, dtype=np.float64)
    left_piezo = np.asarray(left_piezo, dtype=np.float64)
    right_piezo = np.asarray(right_piezo, dtype=np.float64)
    groups = np.asarray(groups)

    valid_c = np.isfinite(left_ctrl) & np.isfinite(right_ctrl)
    valid_p = np.isfinite(left_piezo) & np.isfinite(right_piezo)
    left_ctrl, right_ctrl, groups_c = left_ctrl[valid_c], right_ctrl[valid_c], groups[valid_c]
    left_piezo, right_piezo, groups_p = left_piezo[valid_p], right_piezo[valid_p], groups[valid_p]

    tau_c, _ = stats.kendalltau(left_ctrl, right_ctrl)
    tau_p, _ = stats.kendalltau(left_piezo, right_piezo)
    tau_c = float(tau_c) if tau_c is not None else float("nan")
    tau_p = float(tau_p) if tau_p is not None else float("nan")
    if not (np.isfinite(tau_c) and np.isfinite(tau_p)):
        return float("nan")
    observed = tau_p - tau_c

    common = np.intersect1d(np.unique(groups_c), np.unique(groups_p))
    if len(common) == 0:
        return float("nan")

    idx_c = _idx_by_group(groups_c)
    idx_p = _idx_by_group(groups_p)
    rng = np.random.default_rng(seed)
    b = 0
    for _ in range(n_perm):
        assign_piezo = rng.random(len(common)) > 0.5
        c_idx = np.concatenate([idx_c[g] for g in common[~assign_piezo]])
        p_idx = np.concatenate([idx_p[g] for g in common[assign_piezo]])
        if len(c_idx) < 5 or len(p_idx) < 5:
            continue
        t_c, _ = stats.kendalltau(left_ctrl[c_idx], right_ctrl[c_idx])
        t_p, _ = stats.kendalltau(left_piezo[p_idx], right_piezo[p_idx])
        t_c = float(t_c) if t_c is not None else float("nan")
        t_p = float(t_p) if t_p is not None else float("nan")
        if not (np.isfinite(t_c) and np.isfinite(t_p)):
            continue
        if abs(t_p - t_c) >= abs(observed):
            b += 1
    return (b + 1) / (n_perm + 1)


def _idx_by_group(groups: np.ndarray) -> dict[Any, np.ndarray]:
    idx_by_group: dict[Any, np.ndarray] = {}
    for g in np.unique(groups):
        idx_by_group[g] = np.where(groups == g)[0]
    return idx_by_group


# -----------------------------------------------------------------------------
# Work Package D: Robust portfolio with fair evaluation
# -----------------------------------------------------------------------------


def _group_level_worst_recall(
    selected: list[int],
    left: np.ndarray,
    right: np.ndarray,
    q_star: float,
    groups: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    """Per-group worst-source recall for a global selection.

    Returns (group_labels, recalls).  The source elite set within each group
    uses the group size, so the metric is a grouped analogue of worst-source
    recall.
    """
    selected_set = set(selected)
    labels = np.unique(groups)
    recalls: list[float] = []
    for g in labels:
        idx = np.where(groups == g)[0]
        n_g = len(idx)
        if n_g == 0:
            recalls.append(float("nan"))
            continue
        k_g = max(1, int(math.floor(q_star * n_g)))
        top_j = set(np.argsort(-left[idx], kind="stable")[:k_g])
        top_m = set(np.argsort(-right[idx], kind="stable")[:k_g])
        sel_local = {i for i in range(n_g) if idx[i] in selected_set}
        r_j = len(sel_local & top_j) / k_g
        r_m = len(sel_local & top_m) / k_g
        recalls.append(float(min(r_j, r_m)))
    return labels, np.asarray(recalls, dtype=np.float64)


def _paired_diff_ci_vs_baseline(
    selected: list[int],
    baseline_selected: list[int],
    left: np.ndarray,
    right: np.ndarray,
    q_star: float,
    groups: np.ndarray,
    n_boot: int,
    seed: int,
) -> tuple[float, float, float]:
    """Paired difference (strategy - baseline) CI using group-level recalls."""
    labels_a, rec_a = _group_level_worst_recall(selected, left, right, q_star, groups)
    labels_b, rec_b = _group_level_worst_recall(baseline_selected, left, right, q_star, groups)
    # Labels are the same unique sorted set because both use the same groups.
    return paired_bootstrap_ci_difference(rec_a, rec_b, labels_a, n_boot=n_boot, seed=seed)


def _pareto_frontier(df: pd.DataFrame, recall_col: str, coverage_col: str) -> pd.DataFrame:
    """Flag non-dominated points (higher recall and higher coverage is better)."""
    df = df.copy()
    df["pareto_efficient"] = False
    points = df[[recall_col, coverage_col]].to_numpy(dtype=float)
    for i, (r, c) in enumerate(points):
        dominated = False
        for j, (rj, cj) in enumerate(points):
            if i == j:
                continue
            if rj >= r and cj >= c and (rj > r or cj > c):
                dominated = True
                break
        df.loc[df.index[i], "pareto_efficient"] = not dominated
    return df


def run_wp_d(enriched: pd.DataFrame, cfg: dict[str, Any]) -> dict[str, Any]:
    print("[Phase 7C] Work Package D: robust portfolio with fair evaluation...")
    rp = cfg["robust_portfolio"]
    q_star = rp["q_star"]
    budget_factors = rp["budget_factors"]
    primary_budget = rp["primary_budget_factor"]
    strategies = rp["strategies"]
    metrics = cfg["metrics"]["primary"]
    n_boot = rp["paired_bootstrap_replicates"]
    seed = rp["paired_bootstrap_seed"]
    n_folds = rp["n_folds"]
    cross_seed = rp["cross_eval_seed"]
    tune_seed = rp["disagreement_abstention"]["tune_seed"]
    lambda_grid = rp["disagreement_abstention"]["lambda_grid"]
    n_inner_boot = rp["disagreement_abstention"]["n_inner_boot"]
    panel_masks = _panel_masks(enriched, cfg)

    bench_records: list[dict[str, Any]] = []
    diff_records: list[dict[str, Any]] = []
    full_proc_ci_records: list[dict[str, Any]] = []

    for panel_name, mask in panel_masks.items():
        sub = enriched[mask].copy()
        groups = sub["reduced_formula"].to_numpy()
        pair_ids = sub["pair_id"].astype(str).tolist()
        for metric in metrics:
            left = sub[metric["jarvis_col"]].to_numpy(dtype=float)
            right = sub[metric["mp_col"]].to_numpy(dtype=float)
            valid = np.isfinite(left) & np.isfinite(right)
            if valid.sum() < 20:
                continue
            left_v, right_v, groups_v, pair_ids_v = left[valid], right[valid], groups[valid], [
                p for i, p in enumerate(pair_ids) if valid[i]
            ]

            # Full-panel primary results and sensitivity budgets.
            for budget_factor in budget_factors:
                baseline_selections: dict[str, list[int]] = {}
                baseline_recalls: dict[str, float] = {}
                for strategy in ("jarvis_only", "mp_only"):
                    sel = portfolio_select(strategy, left_v, right_v, q_star, budget_factor)
                    baseline_selections[strategy] = sel
                    baseline_recalls[strategy] = portfolio_metrics(sel, left_v, right_v, q_star)[
                        "worst_source_recall"
                    ]
                better_baseline = (
                    "jarvis_only"
                    if baseline_recalls["jarvis_only"] >= baseline_recalls["mp_only"]
                    else "mp_only"
                )

                # Compute all strategy selections first, then run one full-procedure bootstrap.
                strategy_selections: dict[str, list[int]] = {}
                strategy_metrics: dict[str, dict[str, Any]] = {}
                for strategy in strategies:
                    lam = 0.0
                    if strategy == "disagreement_abstention":
                        unique_groups = np.unique(groups_v)
                        if len(unique_groups) >= 2:
                            lam = tune_disagreement_abstention(
                                left_v,
                                right_v,
                                q_star,
                                budget_factor,
                                lambda_grid,
                                groups_v,
                                n_boot=n_inner_boot,
                                seed=tune_seed,
                            )
                    sel = portfolio_select(
                        strategy, left_v, right_v, q_star, budget_factor, lambda_param=lam
                    )
                    strategy_selections[strategy] = sel
                    strategy_metrics[strategy] = portfolio_metrics(sel, left_v, right_v, q_star)

                full_proc_ci = full_procedure_portfolio_bootstrap_ci(
                    left_v,
                    right_v,
                    q_star,
                    budget_factor,
                    strategies,
                    groups_v,
                    n_boot=n_boot,
                    seed=seed + 2000,
                )
                full_proc_ci["panel"] = panel_name
                full_proc_ci["metric"] = metric["name"]
                full_proc_ci["budget_factor"] = budget_factor
                full_proc_lookup: dict[tuple[str, str], dict[str, Any]] = {
                    (row["strategy"], row["delta_type"]): row.to_dict()
                    for _, row in full_proc_ci.iterrows()
                }

                for strategy in strategies:
                    sel = strategy_selections[strategy]
                    metrics_dict = strategy_metrics[strategy]
                    target_k = max(1, int(math.floor(q_star * len(left_v))))
                    budget = min(len(left_v), int(round(budget_factor * target_k)))
                    lam = 0.0
                    if strategy == "disagreement_abstention":
                        unique_groups = np.unique(groups_v)
                        if len(unique_groups) >= 2:
                            lam = tune_disagreement_abstention(
                                left_v,
                                right_v,
                                q_star,
                                budget_factor,
                                lambda_grid,
                                groups_v,
                                n_boot=n_inner_boot,
                                seed=tune_seed,
                            )

                    diff_point, diff_lo, diff_hi = _paired_diff_ci_vs_baseline(
                        sel,
                        baseline_selections[better_baseline],
                        left_v,
                        right_v,
                        q_star,
                        groups_v,
                        n_boot=n_boot,
                        seed=seed,
                    )
                    mat_diff_point, mat_diff_lo, mat_diff_hi = material_level_paired_diff_ci(
                        sel,
                        baseline_selections[better_baseline],
                        left_v,
                        right_v,
                        q_star,
                        groups_v,
                        n_boot=n_boot,
                        seed=seed + 1000,
                    )

                    fp_j = full_proc_lookup.get((strategy, "delta_j"), {})
                    fp_m = full_proc_lookup.get((strategy, "delta_m"), {})
                    fp_best = full_proc_lookup.get((strategy, "delta_best"), {})

                    is_primary = budget_factor == primary_budget
                    is_coverage_upper_bound = strategy == "balanced_union" and budget_factor == 2.0

                    bench_records.append(
                        {
                            "panel": panel_name,
                            "metric": metric["name"],
                            "eval_mode": "full_panel",
                            "fold": float("nan"),
                            "strategy": strategy,
                            "budget_factor": budget_factor,
                            "is_primary": is_primary,
                            "coverage_upper_bound": is_coverage_upper_bound,
                            "target_k": target_k,
                            "budget": budget,
                            "n": len(left_v),
                            "disagreement_lambda": float(lam) if strategy == "disagreement_abstention" else float("nan"),
                            **metrics_dict,
                            "paired_diff_recall": diff_point,
                            "paired_diff_recall_ci95_low": diff_lo,
                            "paired_diff_recall_ci95_high": diff_hi,
                            "material_paired_diff_recall": mat_diff_point,
                            "material_paired_diff_recall_ci95_low": mat_diff_lo,
                            "material_paired_diff_recall_ci95_high": mat_diff_hi,
                            "full_proc_delta_j_recall": fp_j.get("point", float("nan")),
                            "full_proc_delta_j_recall_ci95_low": fp_j.get("ci95_low", float("nan")),
                            "full_proc_delta_j_recall_ci95_high": fp_j.get("ci95_high", float("nan")),
                            "full_proc_delta_m_recall": fp_m.get("point", float("nan")),
                            "full_proc_delta_m_recall_ci95_low": fp_m.get("ci95_low", float("nan")),
                            "full_proc_delta_m_recall_ci95_high": fp_m.get("ci95_high", float("nan")),
                            "full_proc_delta_best_recall": fp_best.get("point", float("nan")),
                            "full_proc_delta_best_recall_ci95_low": fp_best.get("ci95_low", float("nan")),
                            "full_proc_delta_best_recall_ci95_high": fp_best.get("ci95_high", float("nan")),
                            "baseline_strategy": better_baseline,
                        }
                    )

                    diff_records.append(
                        {
                            "panel": panel_name,
                            "metric": metric["name"],
                            "eval_mode": "full_panel",
                            "strategy": strategy,
                            "budget_factor": budget_factor,
                            "is_primary": is_primary,
                            "coverage_upper_bound": is_coverage_upper_bound,
                            "baseline_strategy": better_baseline,
                            "n_groups": len(np.unique(groups_v)),
                            "paired_diff_recall": diff_point,
                            "paired_diff_recall_ci95_low": diff_lo,
                            "paired_diff_recall_ci95_high": diff_hi,
                            "material_paired_diff_recall": mat_diff_point,
                            "material_paired_diff_recall_ci95_low": mat_diff_lo,
                            "material_paired_diff_recall_ci95_high": mat_diff_hi,
                            "full_proc_delta_j_recall": fp_j.get("point", float("nan")),
                            "full_proc_delta_j_recall_ci95_low": fp_j.get("ci95_low", float("nan")),
                            "full_proc_delta_j_recall_ci95_high": fp_j.get("ci95_high", float("nan")),
                            "full_proc_delta_m_recall": fp_m.get("point", float("nan")),
                            "full_proc_delta_m_recall_ci95_low": fp_m.get("ci95_low", float("nan")),
                            "full_proc_delta_m_recall_ci95_high": fp_m.get("ci95_high", float("nan")),
                            "full_proc_delta_best_recall": fp_best.get("point", float("nan")),
                            "full_proc_delta_best_recall_ci95_low": fp_best.get("ci95_low", float("nan")),
                            "full_proc_delta_best_recall_ci95_high": fp_best.get("ci95_high", float("nan")),
                        }
                    )

                full_proc_ci_records.extend(full_proc_ci.to_dict("records"))

            # 5-fold grouped cross-evaluation at the primary equal budget.
            cv_df = portfolio_cross_evaluation(
                left_v,
                right_v,
                q_star,
                primary_budget,
                strategies,
                groups_v,
                pair_ids_v,
                n_folds=n_folds,
                lambda_grid=lambda_grid,
                n_inner_boot=n_inner_boot,
                cross_eval_seed=cross_seed,
                tune_seed=tune_seed,
            )
            if not cv_df.empty:
                cv_df["panel"] = panel_name
                cv_df["metric"] = metric["name"]
                cv_df["budget_factor"] = primary_budget
                cv_df["is_primary"] = True
                cv_df["coverage_upper_bound"] = (cv_df["strategy"] == "balanced_union") & (
                    primary_budget == 2.0
                )
                cv_df["eval_mode"] = "cv_fold"
                bench_records.extend(cv_df.to_dict("records"))

                # Aggregate paired differences across folds.
                for strategy in cv_df["strategy"].unique():
                    g = cv_df[cv_df["strategy"] == strategy]
                    diffs = g["paired_diff_recall"].to_numpy(dtype=float)
                    if len(diffs) >= 2:
                        rng = np.random.default_rng(seed)
                        boot_means = np.array(
                            [float(np.mean(rng.choice(diffs, size=len(diffs), replace=True))) for _ in range(n_boot)]
                        )
                        diff_lo = float(np.percentile(boot_means, 2.5))
                        diff_hi = float(np.percentile(boot_means, 97.5))
                    else:
                        diff_lo = diff_hi = float("nan")
                    diff_records.append(
                        {
                            "panel": panel_name,
                            "metric": metric["name"],
                            "eval_mode": "cv_mean",
                            "strategy": strategy,
                            "budget_factor": primary_budget,
                            "is_primary": True,
                            "coverage_upper_bound": (strategy == "balanced_union") and (primary_budget == 2.0),
                            "baseline_strategy": "max_fold_baseline",
                            "n_groups": len(g),
                            "paired_diff_recall": float(np.mean(diffs)),
                            "paired_diff_recall_ci95_low": diff_lo,
                            "paired_diff_recall_ci95_high": diff_hi,
                        }
                    )

    bench_df = pd.DataFrame(bench_records)
    diff_df = pd.DataFrame(diff_records)
    full_proc_ci_df = pd.DataFrame(full_proc_ci_records)
    info: dict[str, Any] = {
        "portfolio_benchmark": _write_csv_with_hash(bench_df, RESULT_ROOT / "portfolio_benchmark.csv"),
        "portfolio_paired_differences": _write_csv_with_hash(
            diff_df, RESULT_ROOT / "portfolio_paired_differences.csv"
        ),
    }
    if not full_proc_ci_df.empty:
        info["portfolio_full_procedure_bootstrap"] = _write_csv_with_hash(
            full_proc_ci_df, RESULT_ROOT / "portfolio_full_procedure_bootstrap.csv"
        )

    # Pareto frontier on the full-panel results.
    full_panel = bench_df[bench_df["eval_mode"] == "full_panel"].copy()
    if not full_panel.empty:
        frontier_rows: list[pd.DataFrame] = []
        for (_panel, _metric, _bf), g in full_panel.groupby(["panel", "metric", "budget_factor"]):
            frontier_rows.append(_pareto_frontier(g, "worst_source_recall", "portfolio_coverage"))
        pareto_df = pd.concat(frontier_rows, ignore_index=True)
        info["portfolio_pareto"] = _write_csv_with_hash(pareto_df, RESULT_ROOT / "portfolio_pareto.csv")
    return info


# -----------------------------------------------------------------------------
# Work Package E: Manuscript numbers manifest
# -----------------------------------------------------------------------------


def run_wp_e(cfg: dict[str, Any], summaries: dict[str, pd.DataFrame]) -> dict[str, Any]:
    print("[Phase 7C] Work Package E: manuscript numbers manifest...")
    numbers: dict[str, Any] = {}

    conc = summaries.get("concordance_summary")
    if conc is not None and not conc.empty:
        for _, row in conc.iterrows():
            key = f"{row['panel']}_{row['metric']}_nAUCC"
            numbers[key] = float(row["nAUCC"])

    bands = summaries.get("concordance_bands")
    if bands is not None and not bands.empty:
        for _, row in bands.iterrows():
            key = f"{row['panel']}_{row['metric']}_band_{row['band']}_partial_nAUCC"
            numbers[key] = float(row["partial_nAUCC"])

    hr = summaries.get("high_response_sensitivity")
    if hr is not None and not hr.empty:
        for _, row in hr.iterrows():
            key = f"{row['panel']}_{row['metric']}_frac{row['fraction']:.2f}_{row['method']}"
            numbers[key + "_n"] = int(row["n_selected"])
            numbers[key + "_nAUCC"] = float(row["nAUCC"]) if pd.notna(row["nAUCC"]) else None

    prop = summaries.get("property_controls")
    if prop is not None and not prop.empty:
        ok = prop[prop["status"] == "ok"]
        positive_controls = ok[
            (ok["Delta_tau"].fillna(-np.inf) > 0) | (ok["Delta_nAUCC"].fillna(-np.inf) > 0)
        ]
        numbers["n_positive_controls"] = len(positive_controls)
        numbers["control_attributes"] = positive_controls[["panel", "attribute", "Delta_tau", "Delta_nAUCC"]].to_dict(
            "records"
        )

    prov = summaries.get("control_provenance")
    if prov is not None and not prov.empty:
        numbers["control_same_field_copy_flags"] = prov[prov["same_field_copy_flag"]][["panel", "attribute"]].to_dict(
            "records"
        )

    port = summaries.get("portfolio_benchmark")
    if port is not None and not port.empty:
        ref_metric = cfg["property_controls"]["reference_piezo_metric"]
        primary = port[
            (port["eval_mode"] == "full_panel")
            & (port["is_primary"].eq(True))
            & (port["metric"] == ref_metric)
        ]
        if not primary.empty:
            best = primary.loc[primary["worst_source_recall"].idxmax()]
            numbers["primary_best_strategy"] = str(best["strategy"])
            numbers["primary_best_worst_source_recall"] = float(best["worst_source_recall"])
            numbers["primary_best_full_proc_delta_best_recall"] = float(
                best["full_proc_delta_best_recall"]
            )
            numbers["primary_best_full_proc_delta_best_recall_ci95_low"] = float(
                best["full_proc_delta_best_recall_ci95_low"]
            )
            numbers["primary_best_full_proc_delta_best_recall_ci95_high"] = float(
                best["full_proc_delta_best_recall_ci95_high"]
            )
            numbers["primary_best_metric"] = ref_metric

    numbers["baseline_commit"] = cfg["metadata"]["baseline_commit"]
    numbers["branch"] = cfg["metadata"]["branch"]
    numbers["timestamp"] = _now()

    info = _write_json_with_hash(numbers, RESULT_ROOT / "manuscript_numbers.json")
    return info


# -----------------------------------------------------------------------------
# Work Package F: Third protocol pre-registration
# -----------------------------------------------------------------------------


def run_wp_f(cfg: dict[str, Any]) -> dict[str, Any]:
    print("[Phase 7C] Work Package F: third protocol pre-registration...")
    rp = cfg["robust_portfolio"]
    plan = {
        "plan_name": "third_protocol_adjudication_phase7c",
        "status": "pre_registered_not_executed",
        "branch": cfg["metadata"]["branch"],
        "baseline_commit": cfg["metadata"]["baseline_commit"],
        "candidate_selection": {
            "n_materials": 48,
            "strata": [
                {"name": "consensus_elite", "n": 10, "criteria": "intersection of JARVIS and MP top-10% by F1/F3/F4"},
                {"name": "jarvis_only_elite", "n": 10, "criteria": "top-10% by JARVIS but outside MP top-10%"},
                {"name": "mp_only_elite", "n": 10, "criteria": "top-10% by MP but outside JARVIS top-10%"},
                {"name": "consensus_low", "n": 8, "criteria": "bottom-20% by both sources, non-zero response"},
                {"name": "diversity_balanced", "n": 10, "criteria": "balance crystal system, atom count and P2 membership"},
            ],
            "diversity_constraints": {
                "crystal_systems": ["triclinic", "monoclinic", "orthorhombic", "tetragonal", "trigonal", "hexagonal", "cubic"],
                "max_per_crystal_system": 10,
                "max_per_reduced_formula": 3,
                "require_p2_balance": True,
            },
        },
        "frozen_endpoints": [m["name"] for m in cfg["metrics"]["primary"]],
        "frozen_portfolio_strategies": rp["strategies"],
        "evaluation_metrics": [
            "Recall@k",
            "NDCG@k",
            "minimax_recall_regret",
            "worst_source_normalized_utility",
        ],
        "budget": {
            "n_materials": 48,
            "estimated_core_hours_per_material": "24-96",
            "max_wall_time_weeks": 4,
        },
        "protocol": {
            "code": "ABINIT or Quantum ESPRESSO",
            "functional": "PBEsol or PBE",
            "pseudopotential": "ONCV or PAW (must be documented)",
            "kpoint_density": ">= 1000 k-points per reciprocal atom",
            "ecut": ">= 60 Ha (ABINIT) or equivalent plane-wave cutoff",
            "tensor_convention": "piezoelectric stress e in C/m^2, full Cartesian 3x3x3, engineering Voigt order xx,yy,zz,yz,xz,xy",
            "fail_policy": "If a candidate fails to converge or relax, replace with the next-ranked candidate in the same stratum; document all failures and quarantined materials.",
        },
        "outputs": [
            "raw_total_piezo_tensor_per_protocol",
            "relaxed_structure_and_CIF",
            "convergence_log",
            "transformation_history_json",
            "source_field_provenance_record",
        ],
    }

    path = PROJECT_ROOT / cfg["outputs"]["third_protocol_config"]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(plan, sort_keys=False), encoding="utf-8")
    info = {
        "third_protocol_config": {
            "path": str(path.relative_to(PROJECT_ROOT)),
            "sha256": _sha256_file(path),
        }
    }
    return info


# -----------------------------------------------------------------------------
# Manifest and main
# -----------------------------------------------------------------------------


def _result_hashes() -> list[dict[str, Any]]:
    hashes = []
    for path in sorted(RESULT_ROOT.glob("*.csv")):
        hashes.append({"path": str(path.relative_to(PROJECT_ROOT)), "sha256": _sha256_file(path)})
    for path in sorted(RESULT_ROOT.glob("*.json")):
        hashes.append({"path": str(path.relative_to(PROJECT_ROOT)), "sha256": _sha256_file(path)})
    return hashes


def _key_numbers(summaries: dict[str, pd.DataFrame], cfg: dict[str, Any] | None = None) -> dict[str, Any]:
    numbers: dict[str, Any] = {}
    ref_metric = "F1_Frobenius"
    if cfg is not None:
        ref_metric = cfg.get("property_controls", {}).get("reference_piezo_metric", "F1_Frobenius")
    conc = summaries.get("concordance_summary")
    if conc is not None and not conc.empty:
        row = conc[(conc["panel"] == "P0") & (conc["metric"] == ref_metric)]
        if not row.empty:
            numbers["P0_F1_nAUCC"] = float(row.iloc[0]["nAUCC"])
    bands = summaries.get("concordance_bands")
    if bands is not None and not bands.empty:
        for band in ["elite", "intermediate", "broad"]:
            row = bands[(bands["panel"] == "P0") & (bands["metric"] == ref_metric) & (bands["band"] == band)]
            if not row.empty:
                numbers[f"P0_F1_partial_nAUCC_{band}"] = float(row.iloc[0]["partial_nAUCC"])
    hr = summaries.get("high_response_sensitivity")
    if hr is not None and not hr.empty:
        dual = hr[
            (hr["panel"] == "P0")
            & (hr["metric"] == ref_metric)
            & (hr["method"] == "dual_high")
            & (hr["fraction"] == 0.10)
        ]
        if not dual.empty:
            numbers["P0_F1_dual_high_10pct_nAUCC"] = float(dual.iloc[0]["nAUCC"])
    prop = summaries.get("property_controls")
    if prop is not None and not prop.empty:
        ok = prop[(prop["status"] == "ok") & (prop["panel"] == "P0")]
        pos = ok[(ok["Delta_tau"].fillna(-np.inf) > 0) | (ok["Delta_nAUCC"].fillna(-np.inf) > 0)]
        numbers["n_positive_P0_controls"] = len(pos)
    port = summaries.get("portfolio_benchmark")
    if port is not None and not port.empty:
        primary = port[
            (port["eval_mode"] == "full_panel")
            & (port["is_primary"].eq(True))
            & (port["metric"] == ref_metric)
        ]
        if not primary.empty:
            best = primary.loc[primary["worst_source_recall"].idxmax()]
            numbers["primary_best_worst_source_recall"] = float(best["worst_source_recall"])
            numbers["primary_best_strategy"] = str(best["strategy"])
            numbers["primary_best_full_proc_delta_best_recall"] = float(
                best["full_proc_delta_best_recall"]
            )
            numbers["primary_best_full_proc_delta_best_recall_ci95_low"] = float(
                best["full_proc_delta_best_recall_ci95_low"]
            )
            numbers["primary_best_full_proc_delta_best_recall_ci95_high"] = float(
                best["full_proc_delta_best_recall_ci95_high"]
            )
    return numbers


def write_manifest(summaries: dict[str, pd.DataFrame], cfg: dict[str, Any]) -> dict[str, Any]:
    manifest = {
        "timestamp": _now(),
        "commit": _git_commit(),
        "config_commit": cfg["metadata"]["baseline_commit"],
        "branch": cfg["metadata"]["branch"],
        "files": _result_hashes(),
        "key_numbers": _key_numbers(summaries, cfg),
    }
    path = RESULT_ROOT / "phase7c_manifest.json"
    path.write_text(json.dumps(manifest, indent=2, default=str), encoding="utf-8")
    return {"manifest": {"path": str(path.relative_to(PROJECT_ROOT))}}


def main() -> int:
    parser = argparse.ArgumentParser(description="Run CrossPiezo Phase 7C")
    parser.add_argument("--dry-run", action="store_true", help="Print plan without writing files")
    args = parser.parse_args()

    cfg = _load_config()
    if args.dry_run:
        print("[dry-run] Phase 7C would run A-F work packages and write outputs to:")
        print(f"  artifacts: {ARTIFACT_ROOT}")
        print(f"  results:   {RESULT_ROOT}")
        print(f"  reports:   {REPORT_ROOT}")
        return 0

    ARTIFACT_ROOT.mkdir(parents=True, exist_ok=True)
    RESULT_ROOT.mkdir(parents=True, exist_ok=True)
    REPORT_ROOT.mkdir(parents=True, exist_ok=True)
    (ARTIFACT_ROOT / "figures").mkdir(parents=True, exist_ok=True)

    commit = _git_commit()
    print(f"[Phase 7C] commit={commit}")

    panel_df = load_panel()
    data_root = _resolve_data_root()
    jarvis, mp, _ = load_source_data(data_root)
    enriched = build_enriched_panel(panel_df, jarvis, mp)

    summaries: dict[str, pd.DataFrame] = {}

    info_a = run_wp_a(enriched, cfg)
    summaries["concordance_curve"] = pd.read_csv(RESULT_ROOT / "concordance_curve.csv")
    summaries["concordance_summary"] = pd.read_csv(RESULT_ROOT / "concordance_summary.csv")
    summaries["concordance_bands"] = pd.read_csv(RESULT_ROOT / "concordance_bands.csv")

    info_b = run_wp_b(enriched, cfg)
    summaries["high_response_sensitivity"] = pd.read_csv(RESULT_ROOT / "high_response_sensitivity.csv")

    info_c = run_wp_c(enriched, cfg)
    summaries["property_controls"] = pd.read_csv(RESULT_ROOT / "property_controls.csv")
    summaries["control_provenance"] = pd.read_csv(RESULT_ROOT / "control_provenance.csv")
    if (RESULT_ROOT / "property_control_curves.csv").exists():
        summaries["property_control_curves"] = pd.read_csv(RESULT_ROOT / "property_control_curves.csv")
    if (RESULT_ROOT / "property_control_comparison.csv").exists():
        summaries["property_control_comparison"] = pd.read_csv(RESULT_ROOT / "property_control_comparison.csv")

    info_d = run_wp_d(enriched, cfg)
    summaries["portfolio_benchmark"] = pd.read_csv(RESULT_ROOT / "portfolio_benchmark.csv")
    summaries["portfolio_paired_differences"] = pd.read_csv(RESULT_ROOT / "portfolio_paired_differences.csv")
    if (RESULT_ROOT / "portfolio_pareto.csv").exists():
        summaries["portfolio_pareto"] = pd.read_csv(RESULT_ROOT / "portfolio_pareto.csv")
    if (RESULT_ROOT / "portfolio_full_procedure_bootstrap.csv").exists():
        summaries["portfolio_full_procedure_bootstrap"] = pd.read_csv(
            RESULT_ROOT / "portfolio_full_procedure_bootstrap.csv"
        )

    info_e = run_wp_e(cfg, summaries)
    info_f = run_wp_f(cfg)

    info_manifest = write_manifest(summaries, cfg)

    print("[Phase 7C] Completed.")
    print(
        json.dumps(
            {
                "commit": commit,
                "A": info_a,
                "B": info_b,
                "C": info_c,
                "D": info_d,
                "E": info_e,
                "F": info_f,
                "manifest": info_manifest,
            },
            indent=2,
            default=str,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
